import type { InsertThreatLibrary, InsertControlLibrary } from '@/shared/schema';

export const DATACENTER_THREATS: InsertThreatLibrary[] = [
  {
    name: 'Power Failure - Total',
    category: 'Technical',
    subcategory: 'Infrastructure Failure',
    description: 'Complete loss of utility power and backup systems causing data center downtime',
    riskLevel: 'Critical',
    likelihood: 'Low',
    impact: 'Catastrophic',
    examples: ['Grid failure exceeding UPS runtime', 'Generator failure during outage', 'Fuel delivery failure during extended outage'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Cooling System Failure',
    category: 'Technical',
    subcategory: 'HVAC Failure',
    description: 'Loss of cooling causing servers to overheat and shut down',
    riskLevel: 'Critical',
    likelihood: 'Medium',
    impact: 'Catastrophic',
    examples: ['CRAC unit failure', 'Chiller malfunction', 'Cooling loop leak'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Cyber-Physical Attack',
    category: 'Technical',
    subcategory: 'Cyber Attack',
    description: 'Coordinated attack on both digital systems and physical infrastructure',
    riskLevel: 'Critical',
    likelihood: 'Low',
    impact: 'Catastrophic',
    examples: ['Simultaneous network breach and HVAC manipulation', 'BMS compromise to disable fire suppression', 'Attack on power management systems'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Fire - Server Room',
    category: 'Environmental',
    subcategory: 'Fire Hazard',
    description: 'Fire originating from electrical equipment, batteries, or cabling',
    riskLevel: 'Critical',
    likelihood: 'Low',
    impact: 'Catastrophic',
    examples: ['UPS battery thermal runaway', 'Electrical short in PDU', 'Cable tray fire'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Water Intrusion',
    category: 'Environmental',
    subcategory: 'Water Damage',
    description: 'Water entering server rooms from leaks, floods, or cooling system failures',
    riskLevel: 'Critical',
    likelihood: 'Medium',
    impact: 'Major',
    examples: ['Roof leak during storm', 'Cooling pipe burst', 'Flood from adjacent space'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Unauthorized Physical Access',
    category: 'Human',
    subcategory: 'Physical Breach',
    description: 'Unauthorized individuals gaining access to secure server areas',
    riskLevel: 'Critical',
    likelihood: 'Low',
    impact: 'Major',
    examples: ['Tailgating through mantrap', 'Stolen access credentials', 'Social engineering of security'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Equipment Theft',
    category: 'Human',
    subcategory: 'Theft',
    description: 'Removal of servers, storage arrays, or networking equipment containing sensitive data',
    riskLevel: 'High',
    likelihood: 'Low',
    impact: 'Major',
    examples: ['After-hours server removal', 'Theft during maintenance window', 'Inside job by contractor'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'DDoS Attack',
    category: 'Technical',
    subcategory: 'Cyber Attack',
    description: 'Distributed denial of service attack overwhelming network infrastructure',
    riskLevel: 'High',
    likelihood: 'High',
    impact: 'Major',
    examples: ['Volumetric attack saturating bandwidth', 'Application-layer attack on web services', 'Reflection attack'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Insider Data Exfiltration',
    category: 'Human',
    subcategory: 'Insider Threat',
    description: 'Authorized personnel stealing or leaking sensitive data',
    riskLevel: 'Critical',
    likelihood: 'Medium',
    impact: 'Catastrophic',
    examples: ['Administrator copying customer databases', 'Contractor stealing intellectual property', 'Employee selling data to competitors'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Network Equipment Failure',
    category: 'Technical',
    subcategory: 'Infrastructure Failure',
    description: 'Failure of core routers, switches, or firewalls causing connectivity loss',
    riskLevel: 'High',
    likelihood: 'Medium',
    impact: 'Major',
    examples: ['Core switch failure', 'Router software bug', 'Firewall crash'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Earthquake',
    category: 'Environmental',
    subcategory: 'Natural Disaster',
    description: 'Seismic activity causing structural damage or equipment displacement',
    riskLevel: 'High',
    likelihood: 'Low',
    impact: 'Catastrophic',
    examples: ['Server racks toppling', 'Raised floor collapse', 'Utility infrastructure damage'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Supply Chain Compromise',
    category: 'Operational',
    subcategory: 'Supply Chain',
    description: 'Malicious hardware or software introduced through vendor equipment',
    riskLevel: 'High',
    likelihood: 'Low',
    impact: 'Major',
    examples: ['Backdoored network equipment', 'Counterfeit components with malware', 'Compromised firmware updates'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Human Error - Configuration',
    category: 'Human',
    subcategory: 'Accidental',
    description: 'Accidental misconfiguration causing service disruption or data loss',
    riskLevel: 'High',
    likelihood: 'High',
    impact: 'Major',
    examples: ['Incorrect firewall rule blocking production traffic', 'Accidental deletion of virtual machines', 'Storage array misconfiguration'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Regulatory Audit Failure',
    category: 'Operational',
    subcategory: 'Compliance',
    controlType: 'Detective',
    description: 'Failure to meet SOC 2, ISO 27001, or other compliance requirements resulting in penalties',
    riskLevel: 'Medium',
    likelihood: 'Medium',
    impact: 'Moderate',
    examples: ['Missing access logs', 'Inadequate change management', 'Insufficient backup testing'],
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Ransomware - Infrastructure',
    category: 'Technical',
    subcategory: 'Cyber Attack',
    description: 'Ransomware encrypting production servers, backups, or management systems',
    riskLevel: 'Critical',
    likelihood: 'High',
    impact: 'Catastrophic',
    examples: ['Virtualization platform encryption', 'Backup system compromise', 'SAN encryption'],
    frameworks: ['Data Center'],
    isActive: true
  }
];

export const DATACENTER_CONTROLS: InsertControlLibrary[] = [
  // Physical Security Controls
  {
    name: 'Biometric Mantrap Entry',
    category: 'Physical',
    subcategory: 'Access Control',
    controlType: 'Preventive',
    controlType: 'Preventive',
    description: 'Two-door mantrap with biometric authentication (fingerprint or palm vein) preventing tailgating',
    implementation: 'Install mantrap at primary server room entrance with interlocking doors. Require biometric scan for each door. Monitor for anti-passback violations.',
    cost: 'High',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Security Operations Center (SOC)',
    category: 'Physical',
    subcategory: 'Surveillance',
    controlType: 'Detective',
    description: '24/7 staffed security operations center monitoring all cameras, alarms, and access control systems',
    implementation: 'Dedicated SOC room with video wall displaying all camera feeds, alarm panels, and building management system alerts. 24/7 staffing.',
    cost: 'Very High',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'CCTV - Server Room Interior',
    category: 'Physical',
    subcategory: 'Surveillance',
    controlType: 'Detective',
    description: 'High-definition cameras covering all server racks and aisles with 90-day retention',
    implementation: 'Install cameras with sufficient coverage to read server labels and identify individuals. 4K resolution minimum. Separate storage from production systems.',
    cost: 'Medium',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Perimeter Fence - 8ft with Anti-Climb',
    category: 'Physical',
    subcategory: 'Perimeter Security',
    controlType: 'Preventive',
    description: 'Security fence with anti-climb features and intrusion detection',
    implementation: '8ft chain-link or ornamental fence with angled barbed wire or anti-climb spikes. Install fence-mounted vibration sensors.',
    cost: 'High',
    effectiveness: 6,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Vehicle Barriers - Bollards',
    category: 'Physical',
    subcategory: 'Perimeter Security',
    controlType: 'Preventive',
    description: 'Crash-rated bollards preventing vehicle ramming attacks',
    implementation: 'Install K-rated (K4 minimum) bollards around building perimeter, loading docks, and generator fuel tanks.',
    cost: 'High',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Security Guard - Armed 24/7',
    category: 'Physical',
    subcategory: 'Personnel',
    controlType: 'Preventive',
    description: 'Armed security officers providing access control and incident response',
    implementation: 'Minimum 2 guards on duty at all times. One at lobby desk, one on patrol. Armed per local regulations.',
    cost: 'Very High',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Visitor Escort Policy',
    category: 'Physical',
    subcategory: 'Access Control',
    controlType: 'Preventive',
    description: 'Mandatory escort of all non-employees in secure areas',
    implementation: 'Visitors wear distinctive badges and must be accompanied at all times. Log all visits with timestamp and purpose.',
    cost: 'Low',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Server Rack Locks',
    category: 'Physical',
    subcategory: 'Equipment Security',
    controlType: 'Preventive',
    description: 'Keyed or electronic locks on all server rack cabinet doors',
    implementation: 'Install locks on front and rear rack doors. Use electronic locks with access logging for high-security environments.',
    cost: 'Medium',
    effectiveness: 6,
    frameworks: ['Data Center'],
    isActive: true
  },
  
  // Power Infrastructure Controls
  {
    name: 'Dual Utility Power Feeds',
    category: 'Technical',
    subcategory: 'Power',
    controlType: 'Preventive',
    description: 'Redundant utility power from separate substations',
    implementation: 'Contract with utility for two feeds from different substations. Install automatic transfer switch (ATS) to switch between feeds.',
    cost: 'Very High',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'UPS System - N+1 Redundancy',
    category: 'Technical',
    subcategory: 'Power',
    controlType: 'Preventive',
    description: 'Uninterruptible power supply with one additional unit beyond minimum capacity requirement',
    implementation: 'Size UPS for full data center load. Add one extra UPS module. Configure for parallel redundant operation.',
    cost: 'Very High',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Diesel Generator - N+1',
    category: 'Technical',
    subcategory: 'Power',
    controlType: 'Preventive',
    description: 'Emergency generators with redundancy for extended power outages',
    implementation: 'Install generators sized for 100% data center load plus one extra. Minimum 72-hour fuel capacity on-site.',
    cost: 'Very High',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Generator Fuel Tank - 7 Day Capacity',
    category: 'Technical',
    subcategory: 'Power',
    controlType: 'Preventive',
    description: 'Diesel fuel storage sufficient for one week of continuous operation',
    implementation: 'Install double-wall fuel tank sized for 168 hours of runtime. Fuel delivery contract with 24-hour response.',
    cost: 'High',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Generator Monthly Load Test',
    category: 'Operational',
    subcategory: 'Testing',
    controlType: 'Detective',
    description: 'Monthly testing of generators under full load to ensure reliability',
    implementation: 'Schedule monthly test with load bank. Test each generator individually and in parallel. Document runtime and fuel consumption.',
    cost: 'Low',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'PDU Monitoring',
    category: 'Technical',
    subcategory: 'Power',
    controlType: 'Preventive',
    description: 'Real-time monitoring of power distribution unit load, voltage, and temperature',
    implementation: 'Install intelligent PDUs with per-outlet monitoring. Integrate with DCIM system. Set alerts for 80% capacity.',
    cost: 'Medium',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'A+B Power Distribution',
    category: 'Technical',
    subcategory: 'Power',
    controlType: 'Preventive',
    description: 'Dual power paths to all critical equipment from separate UPS systems',
    implementation: 'Design electrical distribution with A-side and B-side paths. Dual power supplies in all servers. Configure for automatic failover.',
    cost: 'High',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  
  // Cooling Infrastructure Controls
  {
    name: 'CRAC Units - N+1 Redundancy',
    category: 'Technical',
    subcategory: 'Cooling',
    controlType: 'Preventive',
    description: 'Computer room air conditioning with one extra unit beyond minimum requirement',
    implementation: 'Size CRAC units for full heat load. Add one extra unit. Configure for automatic rotation and failover.',
    cost: 'Very High',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Hot Aisle Containment',
    category: 'Technical',
    subcategory: 'Cooling',
    controlType: 'Preventive',
    description: 'Physical barriers containing hot air from server exhausts for efficient cooling',
    implementation: 'Install doors and ceiling panels to enclose hot aisles. Ensure no gaps for hot air escape.',
    cost: 'Medium',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Cold Aisle Containment',
    category: 'Technical',
    subcategory: 'Cooling',
    controlType: 'Preventive',
    description: 'Physical barriers containing cold supply air for server intakes',
    implementation: 'Install doors and ceiling panels to enclose cold aisles. Maintain positive pressure to prevent hot air intrusion.',
    cost: 'Medium',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Temperature & Humidity Monitoring',
    category: 'Technical',
    subcategory: 'Environmental Monitoring',
    controlType: 'Detective',
    description: 'Sensors throughout server room measuring temperature and humidity in real-time',
    implementation: 'Install sensors in hot aisles, cold aisles, and above racks. Alert on deviations from ASHRAE guidelines (18-27°C, 40-60% RH).',
    cost: 'Low',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Chilled Water Plant - Redundant',
    category: 'Technical',
    subcategory: 'Cooling',
    controlType: 'Preventive',
    description: 'Redundant chillers and cooling towers for building chilled water system',
    implementation: 'Install N+1 chillers sized for full cooling load. Redundant cooling towers and pumps. Automatic switchover on failure.',
    cost: 'Very High',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Raised Floor Airflow Management',
    category: 'Technical',
    subcategory: 'Cooling',
    controlType: 'Preventive',
    description: 'Proper sealing and design of raised floor plenum for efficient cold air delivery',
    implementation: 'Seal all cable penetrations with brushed grommets. Install perforated tiles only in cold aisles. Maintain minimum 24" plenum depth.',
    cost: 'Low',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  
  // Fire Suppression Controls
  {
    name: 'VESDA Fire Detection',
    category: 'Technical',
    subcategory: 'Fire Protection',
    controlType: 'Preventive',
    description: 'Very Early Smoke Detection Apparatus using laser-based air sampling for earliest possible fire detection',
    implementation: 'Install air sampling pipes throughout server room. Set multi-level alerts: Alert, Action, Fire 1, Fire 2.',
    cost: 'High',
    effectiveness: 10,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Clean Agent Suppression (FM-200/Novec)',
    category: 'Technical',
    subcategory: 'Fire Protection',
    controlType: 'Preventive',
    description: 'Gas-based fire suppression safe for electronics and personnel',
    implementation: 'Install FM-200 or Novec 1230 system sized for room volume. Include abort switch at exits. Test discharge annually.',
    cost: 'Very High',
    effectiveness: 10,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Pre-Action Sprinkler System',
    category: 'Technical',
    subcategory: 'Fire Protection',
    controlType: 'Preventive',
    description: 'Double-interlock sprinkler system requiring both smoke detection and sprinkler head activation',
    implementation: 'Install dry-pipe pre-action system. Requires smoke detector activation AND thermal head release before water flows.',
    cost: 'High',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Water Leak Detection',
    category: 'Technical',
    subcategory: 'Environmental Monitoring',
    controlType: 'Detective',
    description: 'Sensors detecting water on floor or in ceiling to prevent equipment damage',
    implementation: 'Install rope-style or spot sensors under raised floor, around CRAC units, and near cooling pipes. Alarm to SOC.',
    cost: 'Low',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Fire-Rated Walls & Doors',
    category: 'Physical',
    subcategory: 'Fire Protection',
    controlType: 'Preventive',
    description: '2-hour fire-rated construction isolating data center from adjacent spaces',
    implementation: 'Construct walls and doors to 2-hour fire rating minimum. Seal all penetrations with fire-rated materials.',
    cost: 'High',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  
  // Network Security Controls
  {
    name: 'Next-Gen Firewall with IPS',
    category: 'Technical',
    subcategory: 'Cyber Defense',
    controlType: 'Preventive',
    description: 'Stateful firewall with intrusion prevention, application awareness, and threat intelligence',
    implementation: 'Deploy redundant firewalls at network perimeter. Enable IPS signatures. Configure application-layer filtering.',
    cost: 'High',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'DDoS Mitigation Service',
    category: 'Technical',
    subcategory: 'Cyber Defense',
    controlType: 'Preventive',
    description: 'Cloud-based or on-premise DDoS traffic scrubbing to maintain availability',
    implementation: 'Contract with DDoS mitigation provider (Cloudflare, Akamai). Configure BGP routing for attack traffic redirection.',
    cost: 'Medium',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Network Segmentation - VLANs',
    category: 'Technical',
    subcategory: 'Network Architecture',
    controlType: 'Preventive',
    description: 'Logical separation of production, management, and DMZ networks',
    implementation: 'Create separate VLANs for server production traffic, out-of-band management, storage, and DMZ. Firewall between segments.',
    cost: 'Low',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Network Traffic Analysis (NTA)',
    category: 'Technical',
    subcategory: 'Cyber Defense',
    controlType: 'Preventive',
    description: 'Continuous monitoring and analysis of network flows to detect anomalies',
    implementation: 'Deploy NTA sensors on core switches. Use machine learning to baseline normal traffic. Alert on deviations.',
    cost: 'Medium',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Out-of-Band Management Network',
    category: 'Technical',
    subcategory: 'Network Architecture',
    controlType: 'Preventive',
    description: 'Separate network for server management interfaces (IPMI, iLO) isolated from production',
    implementation: 'Dedicated switches and VLANs for management interfaces. No routing to production network. Jump host access only.',
    cost: 'Medium',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Network Redundancy - N+1 Switches',
    category: 'Technical',
    subcategory: 'Network Architecture',
    controlType: 'Preventive',
    description: 'Redundant core and distribution layer switches with automatic failover',
    implementation: 'Pair of core switches in active-active or active-standby. Dual uplinks from all access switches. Sub-second failover.',
    cost: 'High',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  
  // Cybersecurity Controls
  {
    name: 'Multi-Factor Authentication (MFA)',
    category: 'Technical',
    subcategory: 'Access Control',
    controlType: 'Preventive',
    description: 'Requirement for two authentication factors for all administrative access',
    implementation: 'Enforce MFA for SSH, RDP, VPN, and web consoles. Use hardware tokens or authenticator apps. No SMS-based MFA.',
    cost: 'Low',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Privileged Access Management (PAM)',
    category: 'Technical',
    subcategory: 'Access Control',
    controlType: 'Preventive',
    description: 'System managing, recording, and auditing all privileged account access',
    implementation: 'Deploy PAM solution (CyberArk, BeyondTrust). Check out credentials on-demand. Record all sessions. Rotate passwords automatically.',
    cost: 'High',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Security Information & Event Management (SIEM)',
    category: 'Technical',
    subcategory: 'Monitoring',
    controlType: 'Detective',
    description: 'Centralized logging and correlation of security events across all systems',
    implementation: 'Deploy SIEM platform (Splunk, QRadar). Collect logs from firewalls, servers, applications. Create correlation rules for threats.',
    cost: 'High',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Endpoint Detection & Response (EDR)',
    category: 'Technical',
    subcategory: 'Cyber Defense',
    controlType: 'Preventive',
    description: 'Advanced malware detection and automated response on servers and workstations',
    implementation: 'Deploy EDR agents (CrowdStrike, SentinelOne). Enable behavioral detection. Configure automated isolation of compromised systems.',
    cost: 'Medium',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Vulnerability Scanning - Weekly',
    category: 'Operational',
    subcategory: 'Security Operations',
    controlType: 'Detective',
    description: 'Automated scanning for security vulnerabilities in operating systems and applications',
    implementation: 'Schedule authenticated scans weekly. Prioritize by CVSS score. Patch critical vulnerabilities within 48 hours.',
    cost: 'Low',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Patch Management Process',
    category: 'Operational',
    subcategory: 'Security Operations',
    controlType: 'Detective',
    description: 'Systematic process for testing and deploying security patches',
    implementation: 'Test patches in non-production. Deploy critical patches within 30 days. Document exceptions with compensating controls.',
    cost: 'Low',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Backup System - 3-2-1 Rule',
    category: 'Operational',
    subcategory: 'Business Continuity',
    controlType: 'Corrective',
    description: '3 copies of data, 2 different media types, 1 off-site copy',
    implementation: 'Daily incremental, weekly full backups. One copy on disk, one on tape. Off-site tape storage or cloud backup.',
    cost: 'Medium',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Immutable Backup Storage',
    category: 'Technical',
    subcategory: 'Business Continuity',
    controlType: 'Corrective',
    description: 'Backup storage that cannot be modified or deleted by ransomware',
    implementation: 'Use write-once-read-many (WORM) tape or cloud storage with object lock. Minimum 30-day retention before deletion allowed.',
    cost: 'Medium',
    effectiveness: 10,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Backup Testing - Monthly',
    category: 'Operational',
    subcategory: 'Testing',
    controlType: 'Detective',
    description: 'Regular testing of backup restoration to verify recoverability',
    implementation: 'Monthly test restore of random systems to isolated environment. Document restore time. Test DR failover quarterly.',
    cost: 'Low',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Change Management Process',
    category: 'Operational',
    subcategory: 'Security Operations',
    controlType: 'Detective',
    description: 'Formal approval and documentation of all infrastructure changes',
    implementation: 'Require change request tickets. Peer review of changes. Maintenance windows for high-risk changes. Rollback plan required.',
    cost: 'Low',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  
  // Compliance & Audit Controls
  {
    name: 'SOC 2 Type II Audit - Annual',
    category: 'Operational',
    subcategory: 'Compliance',
    controlType: 'Detective',
    description: 'Annual third-party audit of security controls against AICPA SOC 2 criteria',
    implementation: 'Engage qualified CPA firm. Provide evidence of control operation over 6-12 month period. Remediate exceptions.',
    cost: 'High',
    effectiveness: 10,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'ISO 27001 Certification',
    category: 'Operational',
    subcategory: 'Compliance',
    controlType: 'Detective',
    description: 'International standard for information security management systems',
    implementation: 'Implement ISMS with policies, procedures, and controls. Annual certification audit. Internal audits quarterly.',
    cost: 'High',
    effectiveness: 10,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'PCI-DSS Compliance',
    category: 'Operational',
    subcategory: 'Compliance',
    controlType: 'Detective',
    description: 'Payment Card Industry Data Security Standard for organizations handling card data',
    implementation: 'Quarterly vulnerability scans by approved vendor. Annual penetration test. Quarterly network segmentation testing.',
    cost: 'Medium',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Access Log Retention - 1 Year',
    category: 'Operational',
    subcategory: 'Audit & Logging',
    controlType: 'Detective',
    description: 'Retention of all physical and logical access logs for forensic investigation',
    implementation: 'Store badge swipe logs, server authentication logs, and firewall logs for minimum 12 months. Immutable storage.',
    cost: 'Low',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Security Awareness Training',
    category: 'Operational',
    subcategory: 'Personnel',
    controlType: 'Preventive',
    description: 'Annual mandatory training for all personnel on security policies and threats',
    implementation: 'Online training modules covering phishing, social engineering, physical security. Annual completion required. Track compliance.',
    cost: 'Low',
    effectiveness: 6,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Background Checks - All Staff',
    category: 'Operational',
    subcategory: 'Personnel',
    controlType: 'Preventive',
    description: 'Criminal background checks for all employees and contractors with data center access',
    implementation: 'Conduct background checks before granting access. Renew every 3 years. Document exceptions with compensating controls.',
    cost: 'Low',
    effectiveness: 6,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Incident Response Plan',
    category: 'Operational',
    subcategory: 'Security Operations',
    controlType: 'Detective',
    description: 'Documented procedures for responding to security incidents',
    implementation: 'Define incident severity levels, escalation procedures, and communication plans. Test plan with tabletop exercises annually.',
    cost: 'Low',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Disaster Recovery Plan',
    category: 'Operational',
    subcategory: 'Business Continuity',
    controlType: 'Corrective',
    description: 'Documented procedures for recovering IT systems after catastrophic event',
    implementation: 'Document RPO/RTO for each system. Define recovery procedures. Test failover to DR site annually.',
    cost: 'Low',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Business Continuity Plan',
    category: 'Operational',
    subcategory: 'Business Continuity',
    controlType: 'Corrective',
    description: 'Plan for maintaining critical business operations during facility outage',
    implementation: 'Identify critical processes and dependencies. Define alternate operating procedures. Test with exercises annually.',
    cost: 'Low',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Third-Party Risk Assessment',
    category: 'Operational',
    subcategory: 'Vendor Management',
    controlType: 'Preventive',
    description: 'Evaluation of security posture of vendors with access to systems or data',
    implementation: 'Require security questionnaires (SIG, CAIQ). Review SOC 2 reports. Conduct on-site audits for high-risk vendors.',
    cost: 'Low',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  
  // Building Management Controls
  {
    name: 'Building Management System (BMS)',
    category: 'Technical',
    subcategory: 'Facility Management',
    controlType: 'Detective',
    description: 'Integrated control system managing HVAC, power, lighting, and alarms',
    implementation: 'Deploy BMS with dashboards for all facility systems. Set automated responses (e.g., cooling loss triggers alerts). Secure BMS network.',
    cost: 'High',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Data Center Infrastructure Management (DCIM)',
    category: 'Technical',
    subcategory: 'Facility Management',
    controlType: 'Detective',
    description: 'Software providing real-time monitoring and management of power, cooling, and capacity',
    implementation: 'Deploy DCIM platform integrating power meters, environmental sensors, and asset tracking. Generate capacity planning reports.',
    cost: 'High',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Capacity Planning Process',
    category: 'Operational',
    subcategory: 'Facility Management',
    controlType: 'Detective',
    description: 'Systematic tracking and forecasting of power, cooling, and space utilization',
    implementation: 'Monthly capacity reports showing utilization trends. Alert when power/cooling exceeds 70%. Plan expansion 18 months in advance.',
    cost: 'Low',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Seismic Bracing',
    category: 'Physical',
    subcategory: 'Structural',
    controlType: 'Preventive',
    description: 'Earthquake-resistant mounting for racks, HVAC, and power equipment',
    implementation: 'Install seismic bracing per local building codes. Anchor all racks to floor and ceiling. Brace CRAC units and UPS cabinets.',
    cost: 'Medium',
    effectiveness: 9,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Raised Floor System',
    category: 'Physical',
    subcategory: 'Infrastructure',
    controlType: 'Preventive',
    description: 'Elevated floor providing plenum for cooling airflow and cable management',
    implementation: 'Install raised floor with 24-36" clearance. Heavy-duty tiles (1000+ lb rating). Cable ladder system for structured cabling.',
    cost: 'High',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Cable Management System',
    category: 'Physical',
    subcategory: 'Infrastructure',
    controlType: 'Preventive',
    description: 'Structured system for organizing power and data cables reducing clutter and airflow blockage',
    implementation: 'Install overhead cable trays or under-floor cable ladder. Label all cables. Color-code by type (power=red, network=blue).',
    cost: 'Medium',
    effectiveness: 6,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Asset Inventory Management',
    category: 'Operational',
    subcategory: 'Asset Management',
    controlType: 'Detective',
    description: 'Accurate tracking of all IT equipment with CMDB',
    implementation: 'Maintain configuration management database. Barcode all equipment. Audit inventory quarterly. Track serial numbers and ownership.',
    cost: 'Low',
    effectiveness: 6,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Decommissioning Procedure',
    category: 'Operational',
    subcategory: 'Asset Management',
    controlType: 'Detective',
    description: 'Secure process for retiring equipment including data sanitization',
    implementation: 'Document chain of custody. Wipe drives per NIST 800-88. Physically destroy drives containing sensitive data. Log disposition.',
    cost: 'Low',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  
  // Environmental Controls
  {
    name: 'Fire Extinguishers - Class C',
    category: 'Physical',
    subcategory: 'Fire Protection',
    controlType: 'Preventive',
    description: 'Portable fire extinguishers rated for electrical fires',
    implementation: 'Place CO2 or dry chemical extinguishers throughout data center. Maximum 75ft travel distance. Monthly visual inspection.',
    cost: 'Low',
    effectiveness: 5,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Rodent Control Program',
    category: 'Physical',
    subcategory: 'Environmental',
    controlType: 'Preventive',
    description: 'Preventative measures to exclude rodents that can damage cabling',
    implementation: 'Seal all penetrations. Quarterly pest control service. Inspect for droppings monthly. Bait stations outside building.',
    cost: 'Low',
    effectiveness: 5,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Humidity Control System',
    category: 'Technical',
    subcategory: 'Environmental',
    controlType: 'Preventive',
    description: 'Active humidification and dehumidification maintaining 40-60% relative humidity',
    implementation: 'Install humidifiers in CRAC units. Dehumidification via chilled water. Monitor RH continuously. Alert on out-of-range conditions.',
    cost: 'Medium',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Grounding & Bonding System',
    category: 'Technical',
    subcategory: 'Electrical',
    controlType: 'Preventive',
    description: 'Proper electrical grounding preventing static discharge and electrical faults',
    implementation: 'Install ground bar in data center. Bond all racks, cable trays, and raised floor to ground. Test ground resistance annually.',
    cost: 'Low',
    effectiveness: 8,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Lightning Protection System',
    category: 'Physical',
    subcategory: 'Electrical',
    controlType: 'Preventive',
    description: 'Lightning rods and surge arrestors protecting facility from strikes',
    implementation: 'Install lightning rods on roof. Surge arrestors on utility power feeds. Ground connection to earth ground system.',
    cost: 'Medium',
    effectiveness: 7,
    frameworks: ['Data Center'],
    isActive: true
  },
  {
    name: 'Electrostatic Discharge (ESD) Protection',
    category: 'Physical',
    subcategory: 'Environmental',
    controlType: 'Preventive',
    description: 'Anti-static flooring and grounding straps preventing component damage',
    implementation: 'Install conductive raised floor tiles. Provide ESD wrist straps at workbenches. Maintain 40-60% RH to reduce static.',
    cost: 'Low',
    effectiveness: 6,
    frameworks: ['Data Center'],
    isActive: true
  }
];
