import type { InsertThreatLibrary, InsertControlLibrary } from '@/shared/schema';

export const MANUFACTURING_THREATS: InsertThreatLibrary[] = [
  {
    name: 'Industrial Espionage',
    category: 'Human',
    subcategory: 'Insider Threat',
    description: 'Theft of trade secrets, proprietary processes, or intellectual property by insiders or external actors',
    riskLevel: 'Critical',
    likelihood: 'Medium',
    impact: 'Catastrophic',
    examples: ['Former employee stealing process documentation', 'Competitor plant espionage', 'Foreign intelligence targeting R&D'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Equipment Sabotage',
    category: 'Human',
    subcategory: 'Malicious Insider',
    description: 'Intentional damage to production machinery or control systems to cause downtime or safety incidents',
    riskLevel: 'High',
    likelihood: 'Low',
    impact: 'Major',
    examples: ['Disgruntled employee damaging CNC machines', 'Tampering with safety interlocks', 'Sabotaging quality control systems'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Supply Chain Disruption',
    category: 'Operational',
    subcategory: 'Business Continuity',
    description: 'Interruption of critical material supply or component delivery affecting production schedules',
    riskLevel: 'High',
    likelihood: 'Medium',
    impact: 'Major',
    examples: ['Sole-source supplier failure', 'Transportation strike', 'Raw material shortage', 'Customs delays'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Ransomware Attack - Manufacturing',
    category: 'Technical',
    subcategory: 'Cyber Attack',
    description: 'Malware encrypting production control systems, MES, or ERP systems demanding ransom to restore operations',
    riskLevel: 'Critical',
    likelihood: 'High',
    impact: 'Catastrophic',
    examples: ['WannaCry-style attack on SCADA', 'ERP database encryption', 'PLC controller malware'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Production Line Fire',
    category: 'Environmental',
    subcategory: 'Fire Hazard',
    description: 'Fire originating from manufacturing equipment, chemicals, or electrical systems',
    riskLevel: 'Critical',
    likelihood: 'Medium',
    impact: 'Catastrophic',
    examples: ['Welding spark igniting flammable materials', 'Electrical short in control panel', 'Chemical reaction fire'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'HAZMAT Incident',
    category: 'Environmental',
    subcategory: 'Chemical Exposure',
    description: 'Accidental release or exposure to hazardous materials used in production',
    riskLevel: 'Critical',
    likelihood: 'Low',
    impact: 'Catastrophic',
    examples: ['Chemical spill during transfer', 'Gas leak from storage tank', 'Improper waste handling'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Quality Control Tampering',
    category: 'Human',
    subcategory: 'Product Integrity',
    description: 'Intentional falsification of quality data or bypassing inspection processes',
    riskLevel: 'High',
    likelihood: 'Low',
    impact: 'Major',
    examples: ['Faking test results', 'Skipping critical inspections', 'Altering calibration data'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Theft of Finished Goods',
    category: 'Human',
    subcategory: 'Theft',
    description: 'Unauthorized removal of completed products from warehouse or loading dock',
    riskLevel: 'Medium',
    likelihood: 'Medium',
    impact: 'Moderate',
    examples: ['Employee theft during shipment', 'After-hours warehouse break-in', 'Shipping manipulation'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Counterfeit Components',
    category: 'Operational',
    subcategory: 'Supply Chain',
    description: 'Introduction of fake or substandard parts into production process',
    riskLevel: 'High',
    likelihood: 'Medium',
    impact: 'Major',
    examples: ['Gray market electronic components', 'Fake safety-critical parts', 'Substandard raw materials'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Power Outage - Extended',
    category: 'Technical',
    subcategory: 'Infrastructure Failure',
    description: 'Loss of electrical power exceeding backup generator capacity or runtime',
    riskLevel: 'High',
    likelihood: 'Low',
    impact: 'Major',
    examples: ['Grid failure during heat wave', 'Transformer explosion', 'Natural disaster power loss'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'PLC/SCADA Compromise',
    category: 'Technical',
    subcategory: 'Cyber Attack',
    description: 'Unauthorized access to programmable logic controllers or industrial control systems',
    riskLevel: 'Critical',
    likelihood: 'Medium',
    impact: 'Catastrophic',
    examples: ['Stuxnet-style attack', 'Firmware modification', 'Man-in-the-middle on control network'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'R&D Data Breach',
    category: 'Technical',
    subcategory: 'Data Loss',
    description: 'Unauthorized access to research data, prototypes, or unreleased product designs',
    riskLevel: 'Critical',
    likelihood: 'Medium',
    impact: 'Catastrophic',
    examples: ['Server breach exposing CAD files', 'Stolen prototype', 'Cloud storage leak'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Workplace Violence - Production Floor',
    category: 'Human',
    subcategory: 'Physical Violence',
    description: 'Acts of violence targeting employees in manufacturing environment',
    riskLevel: 'High',
    likelihood: 'Low',
    impact: 'Major',
    examples: ['Active shooter scenario', 'Assault by terminated employee', 'Domestic violence spillover'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Flooding - Equipment Damage',
    category: 'Environmental',
    subcategory: 'Natural Disaster',
    description: 'Water damage to production equipment from flooding or plumbing failure',
    riskLevel: 'High',
    likelihood: 'Low',
    impact: 'Major',
    examples: ['Flash flood entering facility', 'Sprinkler system malfunction', 'Roof leak during storm'],
    frameworks: ['Manufacturing'],
    isActive: true
  },
  {
    name: 'Drone Surveillance',
    category: 'Technical',
    subcategory: 'Espionage',
    description: 'Unauthorized aerial photography or surveillance of facility operations',
    riskLevel: 'Medium',
    likelihood: 'Low',
    impact: 'Moderate',
    examples: ['Competitor drone reconnaissance', 'Facility layout mapping', 'Loading dock activity monitoring'],
    frameworks: ['Manufacturing'],
    isActive: true
  }
];

export const MANUFACTURING_CONTROLS: InsertControlLibrary[] = [
  {
    name: 'Lockout/Tagout (LOTO) Program',
    category: 'Safety',
    subcategory: 'Machine Safety',
    description: 'Comprehensive energy isolation procedures to prevent accidental equipment startup during maintenance',
    controlType: 'Preventive',
    effectiveness: 'High',
    cost: 'Low',
    complexity: 'Low',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Equipment Sabotage'],
    isActive: true
  },
  {
    name: 'R&D Access Control',
    category: 'Physical',
    subcategory: 'Access Control',
    description: 'Restricted badge access, biometric authentication, and visitor logs for research and development areas',
    controlType: 'Preventive',
    effectiveness: 'High',
    cost: 'Medium',
    complexity: 'Medium',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Industrial Espionage', 'R&D Data Breach'],
    isActive: true
  },
  {
    name: 'Production Continuity Plan',
    category: 'Business Continuity',
    subcategory: 'Disaster Recovery',
    description: 'Documented procedures for maintaining production during disruptions, including alternate suppliers and backup equipment',
    controlType: 'Recovery',
    effectiveness: 'High',
    cost: 'Medium',
    complexity: 'High',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Supply Chain Disruption', 'Power Outage - Extended'],
    isActive: true
  },
  {
    name: 'Network Segmentation - OT/IT',
    category: 'Technical',
    subcategory: 'Network Security',
    description: 'Separation of operational technology (SCADA, PLC) from corporate IT network with firewalls and VLANs',
    controlType: 'Preventive',
    effectiveness: 'High',
    cost: 'High',
    complexity: 'High',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Ransomware Attack - Manufacturing', 'PLC/SCADA Compromise'],
    isActive: true
  },
  {
    name: 'Automated Fire Suppression - Production Areas',
    category: 'Environmental',
    subcategory: 'Fire Protection',
    description: 'Sprinkler systems, gas suppression, or foam systems tailored to manufacturing hazards',
    controlType: 'Mitigation',
    effectiveness: 'High',
    cost: 'High',
    complexity: 'Medium',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Production Line Fire'],
    isActive: true
  },
  {
    name: 'HAZMAT Training & Certification',
    category: 'Safety',
    subcategory: 'Employee Training',
    description: 'OSHA-compliant training for employees handling hazardous materials, including emergency response procedures',
    controlType: 'Preventive',
    effectiveness: 'High',
    cost: 'Low',
    complexity: 'Medium',
    frameworks: ['Manufacturing'],
    relatedThreats: ['HAZMAT Incident'],
    isActive: true
  },
  {
    name: 'Quality Control Audit Trail',
    category: 'Operational',
    subcategory: 'Quality Assurance',
    description: 'Digital logging of all quality inspections with tamper-evident records and supervisor reviews',
    controlType: 'Detective',
    effectiveness: 'Medium',
    cost: 'Low',
    complexity: 'Low',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Quality Control Tampering'],
    isActive: true
  },
  {
    name: 'Finished Goods CCTV',
    category: 'Physical',
    subcategory: 'Surveillance',
    description: 'HD camera coverage of warehouse, loading docks, and shipping areas with 30+ day retention',
    controlType: 'Detective',
    effectiveness: 'Medium',
    cost: 'Medium',
    complexity: 'Low',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Theft of Finished Goods'],
    isActive: true
  },
  {
    name: 'Supplier Verification Program',
    category: 'Operational',
    subcategory: 'Supply Chain',
    description: 'Audits of supplier authenticity, component testing, and chain-of-custody documentation',
    controlType: 'Preventive',
    effectiveness: 'Medium',
    cost: 'Medium',
    complexity: 'High',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Counterfeit Components'],
    isActive: true
  },
  {
    name: 'Backup Generator - UPS',
    category: 'Technical',
    subcategory: 'Power Protection',
    description: 'Uninterruptible power supply and diesel generators sized for critical production load with automatic transfer switch',
    controlType: 'Mitigation',
    effectiveness: 'High',
    cost: 'High',
    complexity: 'Medium',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Power Outage - Extended'],
    isActive: true
  },
  {
    name: 'ICS Anomaly Detection',
    category: 'Technical',
    subcategory: 'Cyber Defense',
    description: 'Industrial control system monitoring for unusual PLC commands, firmware changes, or unauthorized network traffic',
    controlType: 'Detective',
    effectiveness: 'High',
    cost: 'High',
    complexity: 'High',
    frameworks: ['Manufacturing'],
    relatedThreats: ['PLC/SCADA Compromise', 'Ransomware Attack - Manufacturing'],
    isActive: true
  },
  {
    name: 'IP Data Loss Prevention',
    category: 'Technical',
    subcategory: 'Data Security',
    description: 'DLP software monitoring CAD file transfers, email attachments, and USB usage in R&D areas',
    controlType: 'Preventive',
    effectiveness: 'Medium',
    cost: 'Medium',
    complexity: 'Medium',
    frameworks: ['Manufacturing'],
    relatedThreats: ['R&D Data Breach', 'Industrial Espionage'],
    isActive: true
  },
  {
    name: 'Active Shooter Response Plan',
    category: 'Safety',
    subcategory: 'Emergency Response',
    description: 'Run-Hide-Fight training, PA lockdown system, and coordination with law enforcement',
    controlType: 'Mitigation',
    effectiveness: 'Medium',
    cost: 'Low',
    complexity: 'Medium',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Workplace Violence - Production Floor'],
    isActive: true
  },
  {
    name: 'Flood Barriers & Drainage',
    category: 'Environmental',
    subcategory: 'Structural Protection',
    description: 'Berms, sandbag staging, elevated equipment platforms, and sump pumps in flood-prone areas',
    controlType: 'Preventive',
    effectiveness: 'Medium',
    cost: 'High',
    complexity: 'Low',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Flooding - Equipment Damage'],
    isActive: true
  },
  {
    name: 'Anti-Drone Detection System',
    category: 'Technical',
    subcategory: 'Perimeter Security',
    description: 'RF detection, radar, or optical sensors to identify unauthorized drones over facility',
    controlType: 'Detective',
    effectiveness: 'Low',
    cost: 'High',
    complexity: 'High',
    frameworks: ['Manufacturing'],
    relatedThreats: ['Drone Surveillance'],
    isActive: true
  }
];
