import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sparkles, Loader2, AlertCircle } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";

interface ExecutiveSummaryCardProps {
  assessmentId: string;
  executiveSummary?: string | null;
}

export function ExecutiveSummaryCard({ assessmentId, executiveSummary }: ExecutiveSummaryCardProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const response = await apiRequest("POST", `/api/assessments/${assessmentId}/analyze`);

      toast({
        title: "Analysis Complete",
        description: "AI Executive Summary generated successfully",
      });

      // Invalidate assessment data to refetch with new summary
      queryClient.invalidateQueries({ queryKey: [`/api/assessments`, assessmentId] });
    } catch (error: any) {
      console.error("Failed to generate analysis:", error);
      toast({
        title: "Analysis Failed",
        description: error.message || "Failed to generate AI analysis. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  // Render markdown-formatted summary with proper structure
  const renderSummary = () => {
    if (!executiveSummary) return null;

    const lines = executiveSummary.split('\n');
    const elements: React.ReactNode[] = [];
    let currentSection: React.ReactNode[] = [];
    let key = 0;

    lines.forEach((line, index) => {
      const trimmedLine = line.trim();
      
      if (trimmedLine.startsWith('### ')) {
        // Flush current section before starting new one
        if (currentSection.length > 0) {
          elements.push(<div key={`section-${key++}`} className="space-y-2">{currentSection}</div>);
          currentSection = [];
        }
        // Add section header
        const headerText = trimmedLine.replace('### ', '');
        elements.push(
          <h3 key={`header-${key++}`} className="text-base font-semibold text-foreground mt-6 first:mt-0 mb-2">
            {headerText}
          </h3>
        );
      } else if (trimmedLine.includes('**')) {
        // Inline bold formatting (e.g., **Bottom Line:** detail text)
        const parts = trimmedLine.split('**');
        const formattedText: React.ReactNode[] = [];
        
        parts.forEach((part, i) => {
          if (i % 2 === 0) {
            // Regular text
            if (part) formattedText.push(<span key={`text-${key++}`}>{part}</span>);
          } else {
            // Bold text
            formattedText.push(<strong key={`bold-${key++}`} className="font-semibold">{part}</strong>);
          }
        });
        
        currentSection.push(
          <p key={`inline-${key++}`} className="text-sm leading-relaxed text-foreground/90">
            {formattedText}
          </p>
        );
      } else if (trimmedLine.startsWith('- ')) {
        // Bullet point
        const text = trimmedLine.substring(2);
        currentSection.push(
          <p key={`bullet-${key++}`} className="text-sm text-foreground/90 pl-4">
            • {text}
          </p>
        );
      } else if (trimmedLine.length > 0) {
        // Regular paragraph
        currentSection.push(
          <p key={`text-${key++}`} className="text-sm leading-relaxed text-foreground/90">
            {trimmedLine}
          </p>
        );
      }
    });

    // Flush remaining section
    if (currentSection.length > 0) {
      elements.push(<div key={`section-${key++}`} className="space-y-2">{currentSection}</div>);
    }

    return elements;
  };

  return (
    <Card className="w-full">
      <CardHeader>
        <div className="flex items-center justify-between gap-4">
          <div className="flex-1">
            <CardTitle className="text-lg sm:text-xl flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-primary" />
              AI Executive Summary
            </CardTitle>
            <CardDescription className="text-xs sm:text-sm mt-1">
              Board-level strategic brief generated by AI
            </CardDescription>
          </div>
          {!executiveSummary && (
            <Button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="shrink-0"
              data-testid="button-generate-summary"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Analyzing...
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4 mr-2" />
                  Analyze Facility
                </>
              )}
            </Button>
          )}
        </div>
      </CardHeader>
      <CardContent>
        {!executiveSummary ? (
          <div className="text-center py-8 space-y-4">
            <AlertCircle className="h-12 w-12 mx-auto text-muted-foreground opacity-50" />
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground font-medium">
                No AI Analysis Generated
              </p>
              <p className="text-xs text-muted-foreground max-w-md mx-auto">
                Complete your facility survey or risk assessment, then click 
                "Analyze Facility" to generate a professional AI-powered executive summary.
              </p>
            </div>
          </div>
        ) : (
          <div className="space-y-4" data-testid="executive-summary-content">
            {renderSummary()}
            
            <div className="pt-4 border-t">
              <Button
                onClick={handleGenerate}
                disabled={isGenerating}
                variant="outline"
                size="sm"
                data-testid="button-regenerate-summary"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="h-3 w-3 mr-2 animate-spin" />
                    Regenerating...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-3 w-3 mr-2" />
                    Regenerate Analysis
                  </>
                )}
              </Button>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
