import { db } from './db';
import { threatLibrary, controlLibrary } from '../shared/schema';

// Additional threats for retail, commercial, and facility assessments
const RETAIL_COMMERCIAL_THREATS = [
  {
    name: "Armed Robbery",
    category: "Theft",
    subcategory: "Violent Theft",
    description: "Theft of cash or property using weapons or threat of violence, typically at retail locations or cash-handling businesses",
    typicalLikelihood: "Low",
    typicalImpact: "Critical",
    asisCode: null,
    mitigation: "Panic buttons, cash management procedures, security guards, CCTV surveillance, robbery prevention training",
    examples: ["Register robbery at retail store", "Bank robbery", "Armored car heist"],
    active: true
  },
  {
    name: "Credit Card Fraud",
    category: "Theft",
    subcategory: "Financial Fraud",
    description: "Fraudulent use of credit card information for unauthorized purchases or transactions",
    typicalLikelihood: "Medium",
    typicalImpact: "Medium",
    asisCode: null,
    mitigation: "EMV chip readers, POS security, transaction monitoring, employee training on fraud detection",
    examples: ["Stolen card usage", "Card skimming at POS", "Chargebacks from fraud"],
    active: true
  },
  {
    name: "Vendor Fraud",
    category: "Theft",
    subcategory: "Supply Chain Fraud",
    description: "Fraudulent activities by vendors including invoice fraud, kickbacks, or delivery of inferior goods",
    typicalLikelihood: "Low",
    typicalImpact: "Medium",
    asisCode: null,
    mitigation: "Vendor background checks, invoice auditing, receiving inspection procedures, dual authorization for payments",
    examples: ["Inflated invoices", "Short deliveries", "Kickback schemes"],
    active: true
  },
  {
    name: "Organized Retail Crime",
    category: "Theft",
    subcategory: "Organized Crime",
    description: "Professional theft rings targeting retail merchandise for resale, often involving multiple perpetrators and coordination",
    typicalLikelihood: "Medium",
    typicalImpact: "High",
    asisCode: null,
    mitigation: "Loss prevention teams, CCTV with facial recognition, EAS systems, coordination with law enforcement",
    examples: ["Flash mob theft", "Booster operations", "Return fraud rings"],
    active: true
  },
  {
    name: "Slip, Trip & Fall",
    category: "Workplace Violence",
    subcategory: "Safety Hazards",
    description: "Injuries to employees or customers from slipping, tripping, or falling due to environmental hazards",
    typicalLikelihood: "High",
    typicalImpact: "Medium",
    asisCode: null,
    mitigation: "Regular inspections, proper signage, maintenance procedures, non-slip surfaces, adequate lighting",
    examples: ["Wet floor slip", "Trip over merchandise", "Fall from elevated surface"],
    active: true
  },
  {
    name: "Cargo Theft",
    category: "Theft",
    subcategory: "Transportation Security",
    description: "Theft of goods during transport, loading/unloading, or from storage yards and distribution centers",
    typicalLikelihood: "Medium",
    typicalImpact: "High",
    asisCode: null,
    mitigation: "GPS tracking, dock security, driver vetting, seal verification, yard lighting and fencing",
    examples: ["Trailer theft from yard", "Hijacking in transit", "Dock pilferage"],
    active: true
  },
  {
    name: "Forklift/Equipment Accident",
    category: "Workplace Violence",
    subcategory: "Safety Hazards",
    description: "Injuries or property damage from forklift or warehouse equipment operation",
    typicalLikelihood: "Medium",
    typicalImpact: "High",
    asisCode: null,
    mitigation: "Operator certification, safety training, equipment maintenance, pedestrian separation, warning systems",
    examples: ["Forklift tip-over", "Pedestrian strike", "Rack collision"],
    active: true
  },
  {
    name: "Fire Hazard",
    category: "Natural Disaster",
    subcategory: "Fire",
    description: "Risk of fire from electrical, chemical, or operational sources in facilities",
    typicalLikelihood: "Low",
    typicalImpact: "Critical",
    asisCode: null,
    mitigation: "Fire detection systems, sprinklers, fire extinguishers, egress planning, hot work permits",
    examples: ["Electrical fire", "Chemical fire", "Kitchen fire"],
    active: true
  },
  {
    name: "Equipment Sabotage",
    category: "Vandalism",
    subcategory: "Operational Disruption",
    description: "Intentional damage to production equipment, machinery, or critical infrastructure to disrupt operations",
    typicalLikelihood: "Low",
    typicalImpact: "High",
    asisCode: null,
    mitigation: "Access control to production areas, CCTV monitoring, employee screening, tamper-evident seals",
    examples: ["Disabled production line", "Chemical contamination", "Computer system damage"],
    active: true
  },
  {
    name: "Data Breach - Physical Access",
    category: "Cyber-Physical",
    subcategory: "Data Security",
    description: "Unauthorized physical access to servers, storage media, or data centers leading to data theft or compromise",
    typicalLikelihood: "Low",
    typicalImpact: "Critical",
    asisCode: null,
    mitigation: "Biometric access, man-traps, data center cages, media destruction procedures, visitor escort policies",
    examples: ["Server room intrusion", "Backup tape theft", "USB device insertion"],
    active: true
  },
  {
    name: "Environmental System Failure",
    category: "Natural Disaster",
    subcategory: "Infrastructure Failure",
    description: "Failure of critical environmental systems such as HVAC, cooling, or humidity control in sensitive facilities",
    typicalLikelihood: "Medium",
    typicalImpact: "High",
    asisCode: null,
    mitigation: "Redundant HVAC systems, environmental monitoring, preventive maintenance, backup cooling",
    examples: ["Data center overheating", "Server room flooding", "Chemical storage temperature failure"],
    active: true
  }
];

// Additional controls for retail, commercial, and facility assessments
const RETAIL_COMMERCIAL_CONTROLS = [
  {
    name: "Electronic Article Surveillance (EAS)",
    category: "Surveillance",
    controlType: "Detective",
    description: "Electronic anti-theft system using tags on merchandise that trigger alarms at exits if not deactivated",
    baseWeight: 3,
    reductionPercentage: 45,
    implementationNotes: "Requires tag application to merchandise, sensor gates at exits, and staff trained to respond to alarms",
    estimatedCost: "$5,000-$25,000 for system, ongoing tag costs",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Point-of-Sale (POS) Security System",
    category: "Surveillance",
    controlType: "Detective",
    description: "Security monitoring of cash registers and POS terminals including exception reporting and transaction analysis",
    baseWeight: 4,
    reductionPercentage: 55,
    implementationNotes: "Integrate with POS software, set up exception alerts, train managers on report analysis",
    estimatedCost: "$2,000-$10,000 depending on integration",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Panic Button / Duress Alarm",
    category: "Intrusion Detection",
    controlType: "Detective",
    description: "Emergency button that silently alerts authorities or security during robbery or violent incident",
    baseWeight: 2,
    reductionPercentage: 20,
    implementationNotes: "Install at strategic locations (registers, offices), connect to monitoring service, test regularly",
    estimatedCost: "$500-$2,000 per location",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Security Tags & Anti-Theft Devices",
    category: "Physical Barriers",
    controlType: "Preventive",
    description: "Hard tags, cables, and anti-theft devices attached to high-value merchandise to deter theft",
    baseWeight: 3,
    reductionPercentage: 40,
    implementationNotes: "Apply to high-value items, train staff on attachment/removal, audit tag inventory",
    estimatedCost: "$0.10-$10 per tag depending on type",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Cash Management Procedures",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Policies for handling, storing, and transporting cash including drop safes, till limits, and counting procedures",
    baseWeight: 4,
    reductionPercentage: 60,
    implementationNotes: "Document procedures, train all cash handlers, enforce till limits, conduct surprise audits",
    estimatedCost: "$1,000-$5,000 for safes and training",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Inventory Audit & Shrink Analysis",
    category: "Procedural Controls",
    controlType: "Detective",
    description: "Regular physical inventory counts and analysis to detect shrinkage from theft, damage, or administrative errors",
    baseWeight: 3,
    reductionPercentage: 35,
    implementationNotes: "Schedule regular cycle counts, analyze shrink by category, investigate anomalies",
    estimatedCost: "Labor cost for counting",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Security Awareness Training",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Training programs for employees on security policies, threat recognition, and incident response",
    baseWeight: 3,
    reductionPercentage: 30,
    implementationNotes: "Include in onboarding, conduct annual refreshers, customize to facility-specific threats",
    estimatedCost: "$50-$200 per employee",
    maintenanceLevel: "Low",
    trainingRequired: false,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Warehouse Management System (WMS)",
    category: "Cyber-Physical Security",
    controlType: "Detective",
    description: "Software system tracking inventory movement, location, and status throughout warehouse operations",
    baseWeight: 4,
    reductionPercentage: 50,
    implementationNotes: "Integrate with RF scanners, train operators, configure exception alerts, audit regularly",
    estimatedCost: "$10,000-$100,000+ depending on scale",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Loading Dock Security Seals",
    category: "Physical Barriers",
    controlType: "Detective",
    description: "Tamper-evident seals on trailers and containers to detect unauthorized access during transport or storage",
    baseWeight: 2,
    reductionPercentage: 25,
    implementationNotes: "Train staff on seal inspection, log seal numbers, investigate broken seals immediately",
    estimatedCost: "$0.50-$5 per seal",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Vehicle Inspection Procedures",
    category: "Procedural Controls",
    controlType: "Detective",
    description: "Inspection protocols for incoming and outgoing vehicles at loading docks and gates",
    baseWeight: 3,
    reductionPercentage: 35,
    implementationNotes: "Create inspection checklist, train security/dock staff, document all inspections",
    estimatedCost: "Minimal - labor only",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Environmental Monitoring System",
    category: "Intrusion Detection",
    controlType: "Detective",
    description: "Sensors monitoring temperature, humidity, water, smoke, and other environmental conditions in critical areas",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Install sensors in server rooms, data centers, storage areas; configure alerts; test regularly",
    estimatedCost: "$2,000-$20,000 depending on coverage",
    maintenanceLevel: "Medium",
    trainingRequired: false,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Redundant Power Systems (UPS/Generator)",
    category: "Physical Barriers",
    controlType: "Preventive",
    description: "Uninterruptible Power Supply and backup generators to maintain operations during power outages",
    baseWeight: 5,
    reductionPercentage: 85,
    implementationNotes: "Size for critical load, test monthly, maintain fuel supply, train staff on transfer procedures",
    estimatedCost: "$5,000-$500,000+ depending on capacity",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Machine Guarding & Safety Interlocks",
    category: "Physical Barriers",
    controlType: "Preventive",
    description: "Physical guards and safety interlocks on machinery to prevent operator injury and equipment damage",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Follow OSHA standards, inspect guards regularly, never bypass interlocks, train operators",
    estimatedCost: "$500-$10,000 per machine",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Hazmat Storage & Handling Procedures",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Policies and controls for safe storage, handling, and disposal of hazardous materials",
    baseWeight: 5,
    reductionPercentage: 80,
    implementationNotes: "Follow EPA/OSHA regulations, maintain SDS library, provide PPE, train handlers, inspect storage areas",
    estimatedCost: "$5,000-$50,000 for compliant storage",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "GPS Tracking",
    category: "Surveillance",
    controlType: "Detective",
    description: "GPS tracking systems for vehicles, equipment, or high-value assets to monitor location and movement",
    baseWeight: 4,
    reductionPercentage: 65,
    implementationNotes: "Install GPS trackers on fleet vehicles, trailers, and high-value mobile assets; monitor via web portal",
    estimatedCost: "$15-$50 per device monthly",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Asset Tracking System",
    category: "Surveillance",
    controlType: "Detective",
    description: "RFID, barcode, or serial number tracking system for inventory and asset location monitoring",
    baseWeight: 4,
    reductionPercentage: 55,
    implementationNotes: "Tag all tracked assets, deploy handheld scanners, integrate with inventory management system",
    estimatedCost: "$10,000-$100,000 depending on scale",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Anonymous Reporting Hotline",
    category: "Procedural Controls",
    controlType: "Detective",
    description: "Confidential phone line or web portal for employees to report security concerns, theft, or policy violations",
    baseWeight: 3,
    reductionPercentage: 40,
    implementationNotes: "Advertise hotline visibility, ensure anonymity, investigate all reports promptly, provide feedback",
    estimatedCost: "$2,000-$10,000 annually for third-party service",
    maintenanceLevel: "Low",
    trainingRequired: false,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Two-Person Rule",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Policy requiring two authorized persons present for high-risk operations like cash handling, high-value shipments, or secure area access",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Document two-person procedures, train staff, enforce strictly for cash/valuables, audit compliance",
    estimatedCost: "Minimal - labor scheduling",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Physical Barrier - Security Cage",
    category: "Physical Barriers",
    controlType: "Preventive",
    description: "Wire mesh or solid wall cages for high-value inventory, equipment, or restricted areas within facilities",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Use heavy-gauge wire mesh or solid panels, install proper locks, limit access to authorized personnel",
    estimatedCost: "$2,000-$20,000 depending on size",
    maintenanceLevel: "Low",
    trainingRequired: false,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Mirrors - Convex Security",
    category: "Surveillance",
    controlType: "Detective",
    description: "Convex mirrors strategically placed to eliminate blind spots and improve visual surveillance in stores and warehouses",
    baseWeight: 2,
    reductionPercentage: 25,
    implementationNotes: "Install at aisle intersections, corners, and blind spots; maintain clean and properly angled",
    estimatedCost: "$25-$150 per mirror",
    maintenanceLevel: "Low",
    trainingRequired: false,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Yard Management System",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Software system tracking trailer locations, movements, and status within yard and loading docks",
    baseWeight: 4,
    reductionPercentage: 60,
    implementationNotes: "Implement check-in/check-out procedures, assign parking locations, track dwell time, audit regularly",
    estimatedCost: "$20,000-$100,000+ for system",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Perimeter Lighting",
    category: "Physical Barriers",
    controlType: "Preventive",
    description: "Adequate exterior lighting along perimeter fences, gates, and vulnerable areas to deter intrusion and enable surveillance",
    baseWeight: 3,
    reductionPercentage: 45,
    implementationNotes: "Maintain minimum 2 foot-candles at perimeter, use motion-activated or dusk-to-dawn fixtures, replace bulbs promptly",
    estimatedCost: "$500-$5,000 per fixture zone",
    maintenanceLevel: "Medium",
    trainingRequired: false,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Yard Lighting",
    category: "Physical Barriers",
    controlType: "Preventive",
    description: "High-intensity lighting for parking lots, loading areas, and storage yards to deter theft and enable surveillance",
    baseWeight: 3,
    reductionPercentage: 50,
    implementationNotes: "Install high-mast or pole lighting, maintain minimum 1-2 foot-candles, cover all vehicle/trailer parking areas",
    estimatedCost: "$2,000-$10,000 per pole",
    maintenanceLevel: "Medium",
    trainingRequired: false,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Kingpin Lock",
    category: "Physical Barriers",
    controlType: "Preventive",
    description: "Heavy-duty lock securing the kingpin of parked trailers to prevent unauthorized movement or theft",
    baseWeight: 3,
    reductionPercentage: 70,
    implementationNotes: "Install on all parked trailers in yard, use high-security padlocks, maintain key control procedures",
    estimatedCost: "$100-$300 per lock",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Dock Leveler Lock",
    category: "Physical Barriers",
    controlType: "Preventive",
    description: "Locking mechanism for dock levelers to prevent unauthorized use and secure loading dock when not in operation",
    baseWeight: 3,
    reductionPercentage: 60,
    implementationNotes: "Install locks on all dock levelers, enforce key control, train dock staff on locking procedures",
    estimatedCost: "$200-$800 per dock",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Vehicle Immobilization System",
    category: "Physical Barriers",
    controlType: "Preventive",
    description: "Electronic or mechanical device preventing unauthorized vehicle movement including ignition kill switches, steering wheel locks, or GPS-based immobilization",
    baseWeight: 4,
    reductionPercentage: 80,
    implementationNotes: "Install on fleet vehicles and trailers, integrate with fleet management system, maintain backup keys securely",
    estimatedCost: "$300-$2,000 per vehicle",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Intrusion Detection System",
    category: "Intrusion Detection",
    controlType: "Detective",
    description: "Integrated system combining door/window contacts, motion sensors, glass break detectors to detect unauthorized facility entry",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Install sensors on all entry points, integrate with alarm panel and monitoring service, test monthly, minimize false alarms",
    estimatedCost: "$3,000-$15,000 for basic system",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Alarm Response Procedures",
    category: "Procedural Controls",
    controlType: "Responsive",
    description: "Documented procedures for responding to security alarm activations including verification, dispatch, and follow-up protocols",
    baseWeight: 3,
    reductionPercentage: 50,
    implementationNotes: "Document response steps, train all staff, establish clear escalation paths, coordinate with monitoring service and law enforcement",
    estimatedCost: "Minimal - documentation and training",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Loading Dock Operating Procedures",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Documented standard operating procedures for loading dock operations including safety, security, and inventory control protocols",
    baseWeight: 3,
    reductionPercentage: 45,
    implementationNotes: "Document all dock processes, train dock workers, enforce compliance, conduct periodic audits",
    estimatedCost: "Minimal - documentation and training",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Shipping & Receiving Procedures",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Documented procedures for incoming and outgoing shipment handling including verification, documentation, and security protocols",
    baseWeight: 3,
    reductionPercentage: 50,
    implementationNotes: "Create detailed SOPs, train shipping/receiving staff, implement verification checks, maintain shipment logs",
    estimatedCost: "Minimal - documentation and training",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  
  // DATACENTER-SPECIFIC CONTROLS
  {
    name: "Biometric Fingerprint",
    category: "Access Control",
    controlType: "Preventive",
    description: "Fingerprint biometric authentication for physical access control, providing unique biological identification",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Deploy enterprise-grade fingerprint scanners at entry points, integrate with access control system, establish enrollment procedures, maintain biometric database security",
    estimatedCost: "$500-$2,000 per reader + $50-$100 per person enrollment",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Biometric Palm Vein",
    category: "Access Control",
    controlType: "Preventive",
    description: "Palm vein biometric authentication using infrared scanning of vein patterns, highly secure and difficult to spoof",
    baseWeight: 5,
    reductionPercentage: 85,
    implementationNotes: "Install palm vein scanners at critical access points, integrate with badge system for multi-factor authentication, establish strict enrollment protocols",
    estimatedCost: "$2,000-$5,000 per reader + integration costs",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Biometric Iris & Facial Recognition",
    category: "Access Control",
    controlType: "Preventive",
    description: "Advanced biometric authentication using iris scanning and/or facial recognition technology for high-security access control",
    baseWeight: 5,
    reductionPercentage: 85,
    implementationNotes: "Deploy iris scanners and/or facial recognition cameras, ensure proper lighting conditions, implement anti-spoofing measures, integrate with access control platform",
    estimatedCost: "$3,000-$10,000 per unit + ongoing license fees",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Multi-Factor Authentication (3 Factors)",
    category: "Access Control",
    controlType: "Preventive",
    description: "Three-factor authentication requiring badge (something you have), biometric (something you are), and PIN (something you know) for critical area access",
    baseWeight: 5,
    reductionPercentage: 90,
    implementationNotes: "Implement layered authentication system, configure access control platform for 3-factor validation, establish strict user provisioning, conduct regular audits",
    estimatedCost: "Integrated system cost: $10,000-$50,000",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Man-Trap Portal System",
    category: "Physical Security",
    controlType: "Preventive",
    description: "Two-door interlock system preventing tailgating by requiring first door to close before second door opens, ensuring one-person-at-a-time entry",
    baseWeight: 5,
    reductionPercentage: 85,
    implementationNotes: "Install at all server floor entry points, integrate with access control and CCTV, configure weight sensors and optical sensors, establish bypass procedures for emergencies",
    estimatedCost: "$15,000-$50,000 per portal",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Cabinet Electronic Locks",
    category: "Access Control",
    controlType: "Preventive",
    description: "Electronic locks on server cabinets/racks with individual access control and audit logging, preventing unauthorized equipment access",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Install on all customer cabinets and high-security racks, integrate with access control system, configure per-cabinet permissions, maintain audit logs",
    estimatedCost: "$200-$800 per cabinet lock",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Cabinet Access Logging",
    category: "Detective Controls",
    controlType: "Detective",
    description: "Automated logging of all cabinet/rack access events including timestamp, user identity, and cabinet ID for audit trail and forensic investigation",
    baseWeight: 3,
    reductionPercentage: 60,
    implementationNotes: "Implement logging system integrated with electronic locks, configure retention policies (minimum 90 days), establish review procedures, enable alerting for anomalous access",
    estimatedCost: "Included with electronic lock system",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Access Logging & Audit Trail",
    category: "Detective Controls",
    controlType: "Detective",
    description: "Comprehensive logging of all physical access events across facility with retention and audit capabilities for compliance and investigation",
    baseWeight: 4,
    reductionPercentage: 65,
    implementationNotes: "Configure access control system for comprehensive logging, establish 1-year retention minimum, implement SIEM integration, conduct quarterly access reviews",
    estimatedCost: "Included with access control platform",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Access Revocation (Immediate)",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Process ensuring physical access credentials are revoked immediately (same day) upon employee termination or role change",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Integrate HR system with access control, establish automated provisioning/deprovisioning workflows, maintain termination checklist, conduct quarterly access audits",
    estimatedCost: "Minimal - process and integration costs",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Visitor Escort (Mandatory)",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Policy requiring all visitors to be escorted by authorized personnel at all times in secure areas, preventing unauthorized access",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Establish escort policy, train all staff on procedures, issue temporary visitor badges, maintain visitor log, enforce no-exceptions policy",
    estimatedCost: "Minimal - policy and training",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Visitor Check-In & ID Verification",
    category: "Access Control",
    controlType: "Preventive",
    description: "Formal visitor registration process including government-issued ID verification, pre-authorization check, and visitor badge issuance",
    baseWeight: 3,
    reductionPercentage: 60,
    implementationNotes: "Implement visitor management system, train reception staff, establish pre-authorization workflow, maintain visitor database, integrate with surveillance",
    estimatedCost: "$1,000-$5,000 for visitor management software",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Customer-Controlled Locks",
    category: "Access Control",
    controlType: "Preventive",
    description: "Provision allowing colocation customers to install their own locks on cabinets/cages for additional security layer and assurance",
    baseWeight: 2,
    reductionPercentage: 40,
    implementationNotes: "Document customer lock policy, provide lock mounting hardware, maintain master key for emergency access, coordinate with customers on access procedures",
    estimatedCost: "Customer-provided",
    maintenanceLevel: "Low",
    trainingRequired: false,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Fire Suppression Clean Agent",
    category: "Environmental Controls",
    controlType: "Responsive",
    description: "Clean agent fire suppression system (FM-200, Novec 1230, Inergen) designed for electronic equipment areas, suppressing fire without water damage",
    baseWeight: 5,
    reductionPercentage: 95,
    implementationNotes: "Install throughout server areas, integrate with fire detection, establish discharge procedures, train staff on evacuation, conduct annual inspections",
    estimatedCost: "$100,000-$500,000 depending on coverage area",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Fire Detection VESDA/Aspirating",
    category: "Environmental Controls",
    controlType: "Detective",
    description: "Very Early Smoke Detection Apparatus (VESDA) or aspirating smoke detection providing earliest possible fire warning in datacenter environments",
    baseWeight: 5,
    reductionPercentage: 90,
    implementationNotes: "Install throughout raised floor and ceiling spaces, configure sensitivity levels, integrate with fire panel and suppression, maintain air sampling pipes, conduct quarterly testing",
    estimatedCost: "$50,000-$200,000 depending on coverage",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Redundant Cooling N+1",
    category: "Environmental Controls",
    controlType: "Preventive",
    description: "Cooling system with one additional redundant unit beyond minimum required capacity, ensuring continued operation during single unit failure",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Design for N+1 capacity, distribute units for load balancing, implement automatic failover, maintain preventive maintenance schedule, monitor performance continuously",
    estimatedCost: "$200,000-$1M+ depending on capacity",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Redundant Cooling 2N",
    category: "Environmental Controls",
    controlType: "Preventive",
    description: "Fully redundant cooling system with two complete independent cooling infrastructures, providing maximum resilience and concurrent maintainability",
    baseWeight: 5,
    reductionPercentage: 95,
    implementationNotes: "Deploy dual independent cooling systems, implement automatic switchover, design for full capacity on either system, maintain both systems in hot standby",
    estimatedCost: "$500,000-$2M+ depending on capacity",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Redundant Power N+1",
    category: "Environmental Controls",
    controlType: "Preventive",
    description: "Power distribution with one additional redundant component beyond minimum required, allowing single component failure without service disruption",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Deploy N+1 UPS and PDU configuration, implement load balancing, configure automatic transfer, maintain all components, test failover quarterly",
    estimatedCost: "$300,000-$1M+ depending on load",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Redundant Power 2N",
    category: "Environmental Controls",
    controlType: "Preventive",
    description: "Fully redundant power infrastructure with two independent power paths from utility to equipment, providing maximum power resilience",
    baseWeight: 5,
    reductionPercentage: 95,
    implementationNotes: "Deploy dual utility feeds, dual UPS systems, dual PDUs, dual power supplies in all critical equipment, implement automated transfer switches, maintain continuous testing",
    estimatedCost: "$800,000-$3M+ depending on capacity",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Generator Backup (48hr Fuel)",
    category: "Environmental Controls",
    controlType: "Responsive",
    description: "Backup generator system with 48+ hours fuel capacity at full load, ensuring continued operation during extended utility outages",
    baseWeight: 5,
    reductionPercentage: 90,
    implementationNotes: "Size generator for full facility load, install fuel storage for 48+ hours, implement automatic transfer switch, establish fuel delivery contract, test monthly under load",
    estimatedCost: "$200,000-$1M+ depending on capacity",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "UPS Battery Backup",
    category: "Environmental Controls",
    controlType: "Responsive",
    description: "Uninterruptible Power Supply providing battery backup during utility transitions and short outages, bridging to generator startup",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Size UPS for runtime to generator startup (typically 5-15 minutes), implement battery monitoring, establish replacement schedule, test transfer monthly",
    estimatedCost: "$100,000-$800,000 depending on capacity",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Hot/Cold Aisle Containment",
    category: "Environmental Controls",
    controlType: "Preventive",
    description: "Physical separation of hot and cold air streams in datacenter to improve cooling efficiency and reduce risk of hotspots",
    baseWeight: 3,
    reductionPercentage: 50,
    implementationNotes: "Install containment system (cold aisle preferred), seal gaps, configure airflow direction, monitor temperatures, maintain doors/curtains",
    estimatedCost: "$50-$200 per linear foot",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Water Leak Detection",
    category: "Environmental Controls",
    controlType: "Detective",
    description: "Sensors under raised floors and near water sources to detect leaks early and prevent equipment damage",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Install rope sensors or point sensors in all areas with plumbing, integrate with BMS, establish alarm response procedures, test quarterly",
    estimatedCost: "$5,000-$20,000 depending on coverage",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Temperature & Humidity Monitoring",
    category: "Environmental Controls",
    controlType: "Detective",
    description: "Continuous monitoring of temperature and humidity levels with alarming to prevent equipment damage and ensure optimal conditions",
    baseWeight: 4,
    reductionPercentage: 65,
    implementationNotes: "Deploy sensors throughout facility, configure thresholds per ASHRAE guidelines, integrate with BMS and alerting system, log all data for trending",
    estimatedCost: "$500-$2,000 per sensor + BMS integration",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "CCTV Perimeter (Datacenter)",
    category: "Surveillance",
    controlType: "Detective",
    description: "CCTV camera coverage of entire datacenter perimeter for intrusion detection and forensic investigation",
    baseWeight: 4,
    reductionPercentage: 65,
    implementationNotes: "Deploy cameras with overlapping fields of view, ensure adequate lighting, implement motion detection, integrate with VMS, maintain 90-day retention",
    estimatedCost: "$1,000-$3,000 per camera + NVR",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "CCTV All Entry/Exit Points",
    category: "Surveillance",
    controlType: "Detective",
    description: "CCTV coverage of all facility entry and exit points for access monitoring and incident investigation",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Install cameras at all doors with clear facial capture capability, integrate with access control, ensure adequate lighting, maintain extended retention",
    estimatedCost: "$1,500-$4,000 per location",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "CCTV Server Floor Aisles",
    category: "Surveillance",
    controlType: "Detective",
    description: "CCTV coverage of all server floor aisles to monitor activity and deter/detect unauthorized equipment access",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Deploy cameras covering all aisles, configure for continuous recording, integrate with access control events, enable motion detection analytics",
    estimatedCost: "$1,000-$2,500 per camera",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "CCTV Man-Trap Portals",
    category: "Surveillance",
    controlType: "Detective",
    description: "CCTV cameras positioned at man-trap portals to capture clear facial images and verify single-person entry",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Install cameras with facial capture capability inside man-traps, integrate with access control, configure recording on portal activation, maintain evidence-grade video quality",
    estimatedCost: "$2,000-$5,000 per portal",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Hands-On-Server Cameras",
    category: "Surveillance",
    controlType: "Detective",
    description: "Cameras positioned to capture hands-on-server activity at customer cabinets, deterring and detecting unauthorized equipment manipulation",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Deploy cameras with clear view of cabinet fronts and rear, configure for continuous recording, integrate with cabinet access events, enable analytics for tampering detection",
    estimatedCost: "$1,500-$3,000 per cabinet area",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Video Retention 90 Days",
    category: "Surveillance",
    controlType: "Detective",
    description: "Video surveillance storage with minimum 90-day retention for compliance and investigation support",
    baseWeight: 3,
    reductionPercentage: 50,
    implementationNotes: "Size storage for 90+ days at required resolution, implement automated retention management, establish backup procedures, ensure compliance with data protection regulations",
    estimatedCost: "$5,000-$50,000 depending on camera count and resolution",
    maintenanceLevel: "Low",
    trainingRequired: false,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Video Analytics & Behavior Detection",
    category: "Surveillance",
    controlType: "Detective",
    description: "AI-powered video analytics detecting anomalous behaviors such as loitering, tailgating, perimeter breach, and unusual patterns",
    baseWeight: 4,
    reductionPercentage: 65,
    implementationNotes: "Implement analytics software, configure behavior rules and sensitivity, integrate with alarm management, train operators on alert handling, tune to reduce false positives",
    estimatedCost: "$500-$2,000 per camera license + annual fees",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Facial Recognition System",
    category: "Surveillance",
    controlType: "Preventive",
    description: "Facial recognition integrated with access control and surveillance for identity verification and watchlist alerting",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Deploy facial recognition cameras and software, enroll authorized personnel, configure watchlists, integrate with access control, ensure compliance with privacy regulations",
    estimatedCost: "$5,000-$20,000 + ongoing license fees",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Network Segmentation (Customer Isolation)",
    category: "Logical Security",
    controlType: "Preventive",
    description: "Network segmentation isolating customer environments from each other and from management networks, preventing lateral movement and cross-contamination",
    baseWeight: 5,
    reductionPercentage: 85,
    implementationNotes: "Implement VLANs or VRFs per customer, configure firewall policies, establish jump boxes for administrative access, conduct penetration testing to verify isolation",
    estimatedCost: "Included in network infrastructure",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Out-of-Band Management",
    category: "Logical Security",
    controlType: "Preventive",
    description: "Dedicated out-of-band network for infrastructure management, ensuring access to critical systems even during network outages or attacks",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Deploy separate physical network for management, implement strong authentication, restrict access to authorized administrators, maintain separate internet connection",
    estimatedCost: "$10,000-$50,000 for infrastructure",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Jump Box Access Controlled",
    category: "Logical Security",
    controlType: "Preventive",
    description: "Hardened jump boxes (bastion hosts) providing controlled administrative access to datacenter infrastructure with full session logging",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Deploy jump boxes with MFA, implement session recording, configure privileged access management, establish least privilege access, conduct regular security audits",
    estimatedCost: "$5,000-$20,000 + PAM licensing",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Remote Hands Procedures",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Documented procedures for remote hands services ensuring controlled equipment access, verification, and customer authorization",
    baseWeight: 3,
    reductionPercentage: 60,
    implementationNotes: "Document remote hands workflows, implement ticketing system, establish customer authorization process, train remote hands staff, maintain activity logs",
    estimatedCost: "Minimal - documentation and training",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Logical Access Integration",
    category: "Logical Security",
    controlType: "Preventive",
    description: "Integration between physical access control and logical access systems, correlating physical presence with logical access for enhanced security",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Integrate PACS with IAM system, implement context-aware authentication, configure policies requiring physical presence for sensitive operations, maintain audit correlation",
    estimatedCost: "$20,000-$100,000 for integration",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Vulnerability Assessment (Regular)",
    category: "Detective Controls",
    controlType: "Detective",
    description: "Regular vulnerability assessments of physical and logical security systems to identify and remediate weaknesses",
    baseWeight: 4,
    reductionPercentage: 65,
    implementationNotes: "Conduct quarterly assessments, engage qualified third-party assessors, prioritize findings, establish remediation SLAs, track metrics over time",
    estimatedCost: "$10,000-$50,000 per assessment",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Penetration Testing (Physical)",
    category: "Detective Controls",
    controlType: "Detective",
    description: "Physical penetration testing simulating real-world attack scenarios to validate effectiveness of physical security controls",
    baseWeight: 5,
    reductionPercentage: 75,
    implementationNotes: "Conduct annual physical pen tests, engage certified red team, define scope and rules of engagement, remediate findings, retest critical vulnerabilities",
    estimatedCost: "$15,000-$75,000 per test",
    maintenanceLevel: "Low",
    trainingRequired: false,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Perimeter Barrier & Standoff Distance",
    category: "Physical Security",
    controlType: "Preventive",
    description: "Physical perimeter barrier (fencing, walls) with adequate standoff distance from building to deter and delay intruders",
    baseWeight: 3,
    reductionPercentage: 55,
    implementationNotes: "Install 8+ foot fencing with anti-climb features, maintain 50+ foot standoff where possible, ensure clear zones, integrate with intrusion detection and CCTV",
    estimatedCost: "$50-$150 per linear foot",
    maintenanceLevel: "Low",
    trainingRequired: false,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Perimeter Intrusion Detection (Datacenter)",
    category: "Physical Security",
    controlType: "Detective",
    description: "Perimeter intrusion detection using fence sensors, buried sensors, microwave, or infrared to detect perimeter breaches",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Deploy redundant detection technologies, integrate with CCTV for video verification, configure alarm zones, establish response procedures, tune to minimize false alarms",
    estimatedCost: "$100,000-$500,000 depending on perimeter size",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Vehicle Barriers (Bollards)",
    category: "Physical Security",
    controlType: "Preventive",
    description: "Crash-rated bollards or wedge barriers preventing vehicle-borne attacks on datacenter facilities",
    baseWeight: 4,
    reductionPercentage: 80,
    implementationNotes: "Install crash-rated barriers (K4/K8/K12 rating), position at all vehicle approach paths, maintain clear zones, test retractable barriers regularly",
    estimatedCost: "$5,000-$20,000 per barrier",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Security Guard 24/7",
    category: "Physical Security",
    controlType: "Preventive",
    description: "24/7 staffed security guard force providing access control, patrol, monitoring, and incident response",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Hire licensed security personnel, establish post orders, train on procedures and systems, implement guard tour system, conduct regular performance reviews",
    estimatedCost: "$150,000-$300,000 per guard position annually",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "NOC/SOC 24/7 Monitoring",
    category: "Detective Controls",
    controlType: "Detective",
    description: "24/7 Network Operations Center (NOC) or Security Operations Center (SOC) monitoring video, alarms, and infrastructure",
    baseWeight: 5,
    reductionPercentage: 80,
    implementationNotes: "Staff 24/7 monitoring center, integrate all security systems, establish incident response procedures, train operators on all systems, maintain detailed logs",
    estimatedCost: "$300,000-$600,000 annually for staffing",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Background Checks Level 2",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Comprehensive Level 2 background checks including criminal, credit, employment history, and education verification for datacenter staff",
    baseWeight: 4,
    reductionPercentage: 65,
    implementationNotes: "Conduct Level 2 checks for all staff with datacenter access, establish disqualifying criteria, maintain records per regulations, conduct periodic re-checks",
    estimatedCost: "$100-$300 per person",
    maintenanceLevel: "Low",
    trainingRequired: false,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Insider Threat Monitoring Program",
    category: "Detective Controls",
    controlType: "Detective",
    description: "Program monitoring for insider threat indicators including anomalous access patterns, policy violations, and behavioral changes",
    baseWeight: 4,
    reductionPercentage: 60,
    implementationNotes: "Implement user behavior analytics, establish baseline patterns, configure alerting on anomalies, train supervisors on indicators, maintain investigation procedures",
    estimatedCost: "$20,000-$100,000 for UBA software + staffing",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Two-Person Rule (Sensitive Ops)",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Policy requiring two authorized personnel present for sensitive operations such as equipment moves, cabling changes, and drive destruction",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Document two-person rule policy, train all staff, enforce compliance, maintain logs of two-person activities, establish exceptions process for emergencies",
    estimatedCost: "Minimal - policy and training",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Clean Desk Clear Screen Policy",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Policy requiring clean desks and locked/logged-out screens when workstations are unattended to prevent information disclosure",
    baseWeight: 2,
    reductionPercentage: 40,
    implementationNotes: "Document policy, train all staff, implement automatic screen lock after inactivity, conduct periodic compliance checks, enforce disciplinary action for violations",
    estimatedCost: "Minimal - policy and training",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "NDA & Confidentiality Agreements",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Non-disclosure and confidentiality agreements signed by all employees and contractors with access to sensitive information",
    baseWeight: 2,
    reductionPercentage: 30,
    implementationNotes: "Develop comprehensive NDA templates, require signatures before granting access, maintain signed copies, include in termination procedures, enforce legally when breached",
    estimatedCost: "Minimal - legal review and documentation",
    maintenanceLevel: "Low",
    trainingRequired: false,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Vendor Vetting & Background Checks",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Background check and vetting process for vendors and contractors requiring datacenter access",
    baseWeight: 3,
    reductionPercentage: 55,
    implementationNotes: "Establish vendor vetting procedures, require background checks for vendor personnel, maintain approved vendor list, escort unvetted vendors, review annually",
    estimatedCost: "$100-$300 per vendor employee",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Secure Disposal & Drive Shredding",
    category: "Procedural Controls",
    controlType: "Preventive",
    description: "Secure disposal procedures including witnessed drive shredding with certificate of destruction to prevent data theft from decommissioned equipment",
    baseWeight: 4,
    reductionPercentage: 85,
    implementationNotes: "Contract with certified destruction vendor, establish chain of custody procedures, provide destruction certificates to customers, maintain destruction logs, conduct periodic audits",
    estimatedCost: "$5-$20 per drive + service fees",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Compliance Audit (Annual)",
    category: "Detective Controls",
    controlType: "Detective",
    description: "Annual third-party compliance audits (SOC 2, ISO 27001, PCI-DSS) validating security control effectiveness and identifying gaps",
    baseWeight: 4,
    reductionPercentage: 60,
    implementationNotes: "Engage qualified auditors, prepare documentation, remediate findings within SLA, maintain continuous compliance monitoring, provide reports to customers",
    estimatedCost: "$25,000-$150,000 per audit depending on scope",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Incident Response Plan (Documented)",
    category: "Procedural Controls",
    controlType: "Responsive",
    description: "Documented incident response plan with defined roles, procedures, and escalation paths for security incidents",
    baseWeight: 3,
    reductionPercentage: 55,
    implementationNotes: "Develop comprehensive IRP, train response team, conduct tabletop exercises, update annually, integrate with customer notification procedures",
    estimatedCost: "$5,000-$25,000 for plan development",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Incident Response Team 24/7",
    category: "Detective Controls",
    controlType: "Responsive",
    description: "24/7 incident response team capable of responding to security incidents with defined response time SLAs",
    baseWeight: 4,
    reductionPercentage: 70,
    implementationNotes: "Staff 24/7 response team, establish on-call rotation, define response time SLAs, train on procedures and tools, conduct regular drills",
    estimatedCost: "$200,000-$400,000 annually for staffing",
    maintenanceLevel: "Medium",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Disaster Recovery Site",
    category: "Business Continuity",
    controlType: "Responsive",
    description: "Geographically separate disaster recovery datacenter site providing failover capability for critical operations",
    baseWeight: 5,
    reductionPercentage: 90,
    implementationNotes: "Establish DR site with adequate capacity, implement replication, test failover procedures quarterly, maintain hot/warm/cold standby per requirements",
    estimatedCost: "$500,000-$5M+ depending on capacity",
    maintenanceLevel: "High",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Business Continuity Plan",
    category: "Business Continuity",
    controlType: "Responsive",
    description: "Documented business continuity plan ensuring continued operations during disruptions with defined recovery time objectives (RTO)",
    baseWeight: 4,
    reductionPercentage: 65,
    implementationNotes: "Develop comprehensive BCP, define RTOs and RPOs, test plan annually, train staff on roles, update after tests or changes",
    estimatedCost: "$10,000-$50,000 for plan development",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: false,
    active: true
  },
  {
    name: "Emergency Power Off (EPO)",
    category: "Environmental Controls",
    controlType: "Responsive",
    description: "Emergency Power Off system allowing immediate power shutdown to entire facility or zones in emergency situations (fire, flooding, safety)",
    baseWeight: 3,
    reductionPercentage: 50,
    implementationNotes: "Install EPO buttons at strategic locations, clearly label and protect from accidental activation, train staff on when to use, test annually, document procedures",
    estimatedCost: "$5,000-$20,000",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  },
  {
    name: "Seismic Protection",
    category: "Environmental Controls",
    controlType: "Preventive",
    description: "Seismic bracing and earthquake protection measures for equipment, racks, and infrastructure in seismic zones",
    baseWeight: 4,
    reductionPercentage: 75,
    implementationNotes: "Install seismic bracing per local codes, anchor all racks and equipment, use flexible connections for utilities, conduct seismic assessment, test restraints",
    estimatedCost: "$50,000-$250,000 depending on facility size",
    maintenanceLevel: "Low",
    trainingRequired: true,
    maintenanceRequired: true,
    active: true
  }
];

async function seedRetailCommercialLibraries() {
  try {
    console.log('Starting retail/commercial threat and control library expansion...');
    
    // Insert new threats (will skip duplicates if name already exists)
    let threatsAdded = 0;
    for (const threat of RETAIL_COMMERCIAL_THREATS) {
      try {
        await db.insert(threatLibrary).values(threat);
        threatsAdded++;
      } catch (error: any) {
        if (error.code !== '23505') { // Not a duplicate key error
          console.error(`Error inserting threat "${threat.name}":`, error.message);
        }
      }
    }
    console.log(`✓ Added ${threatsAdded} new threats to threat_library`);
    
    // Insert new controls (will skip duplicates if name already exists)
    let controlsAdded = 0;
    for (const control of RETAIL_COMMERCIAL_CONTROLS) {
      try {
        await db.insert(controlLibrary).values(control);
        controlsAdded++;
      } catch (error: any) {
        if (error.code !== '23505') { // Not a duplicate key error
          console.error(`Error inserting control "${control.name}":`, error.message);
        }
      }
    }
    console.log(`✓ Added ${controlsAdded} new controls to control_library`);
    
    console.log('\n✓ Library expansion complete!');
    console.log(`Total new entries: ${threatsAdded} threats + ${controlsAdded} controls`);
    
    process.exit(0);
  } catch (error) {
    console.error('Error expanding libraries:', error);
    process.exit(1);
  }
}

seedRetailCommercialLibraries();
