import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { FileText, Download, Eye, Share, Mail } from "lucide-react";

interface ReportConfig {
  id: string;
  title: string;
  description: string;
  format: "pdf" | "docx" | "html";
  sections: string[];
  status: "ready" | "generating" | "error";
  lastGenerated?: string;
  size?: string;
}

const mockReports: ReportConfig[] = [
  {
    id: "exec-summary",
    title: "Executive Summary",
    description: "High-level overview for management with key findings and recommendations",
    format: "pdf",
    sections: ["Risk Overview", "Critical Findings", "Recommendations", "Action Items"],
    status: "ready",
    lastGenerated: "Dec 20, 2024",
    size: "2.3 MB"
  },
  {
    id: "detailed-technical",
    title: "Detailed Technical Report", 
    description: "Comprehensive technical assessment with all findings and evidence",
    format: "pdf",
    sections: ["Assessment Methodology", "Detailed Findings", "Risk Analysis", "Evidence", "Appendices"],
    status: "ready",
    lastGenerated: "Dec 20, 2024",
    size: "8.7 MB"
  },
  {
    id: "compliance-report",
    title: "Compliance Checklist",
    description: "Regulatory compliance mapping and gap analysis",
    format: "docx",
    sections: ["Compliance Framework", "Gap Analysis", "Remediation Plan"],
    status: "generating",
  }
];

interface ReportGeneratorProps {
  assessmentId?: string;
  reports?: ReportConfig[];
  onGenerate?: (reportId: string) => void;
  onDownload?: (reportId: string) => void;
  onShare?: (reportId: string) => void;
}

export function ReportGenerator({
  assessmentId = "sample-001",
  reports = mockReports,
  onGenerate,
  onDownload,
  onShare
}: ReportGeneratorProps) {
  const { toast } = useToast();
  const [previewOpen, setPreviewOpen] = useState(false);
  const [previewReport, setPreviewReport] = useState<ReportConfig | null>(null);
  
  const handleGenerate = (reportId: string) => {
    console.log(`Generating report: ${reportId}`);
    onGenerate?.(reportId);
  };

  const handlePreview = (report: ReportConfig) => {
    setPreviewReport(report);
    setPreviewOpen(true);
  };

  const handleDownload = (reportId: string) => {
    const report = reports.find(r => r.id === reportId);
    if (!report) return;

    const reportContent = `
SECURITY ASSESSMENT REPORT
${report.title}
${'='.repeat(report.title.length + 25)}

Assessment ID: ${assessmentId}
Report Format: ${report.format.toUpperCase()}
Generated: ${report.lastGenerated || new Date().toLocaleDateString()}
Status: ${report.status.toUpperCase()}

DESCRIPTION
-----------
${report.description}

REPORT SECTIONS
---------------
${report.sections.map((section, idx) => `${idx + 1}. ${section}`).join('\n')}

${report.format === 'pdf' ? '\n[PDF Generation Note: This is a placeholder text file. Full PDF generation with formatting, charts, and images would be implemented using a PDF library like jsPDF or server-side PDF generation.]' : ''}
${report.format === 'docx' ? '\n[DOCX Generation Note: This is a placeholder text file. Full DOCX generation with formatting and styling would be implemented using a library like docx or server-side DOCX generation.]' : ''}
${report.format === 'html' ? '\n[HTML Generation Note: Full HTML report with interactive elements and embedded charts would be generated.]' : ''}

METADATA
--------
Report ID: ${report.id}
${report.size ? `File Size: ${report.size}` : ''}

---
Generated by Physical Security Risk Assessment Platform
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.id}-${assessmentId}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast({
      title: "Download Started",
      description: `${report.title} is being downloaded as a text file.`,
    });

    onDownload?.(reportId);
  };

  const handleShare = (reportId: string) => {
    console.log(`Sharing report: ${reportId}`);
    onShare?.(reportId);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Report Generator
          </CardTitle>
          <p className="text-sm text-muted-foreground">
            Generate professional security assessment reports in multiple formats
          </p>
        </CardHeader>
      </Card>

      <div className="grid gap-4">
        {reports.map((report) => (
          <Card key={report.id} data-testid={`card-report-${report.id}`}>
            <CardHeader>
              <div className="flex items-start justify-between">
                <div className="space-y-1">
                  <CardTitle className="text-base">{report.title}</CardTitle>
                  <p className="text-sm text-muted-foreground">
                    {report.description}
                  </p>
                </div>
                
                <div className="flex items-center gap-2">
                  <Badge variant="outline">
                    {report.format.toUpperCase()}
                  </Badge>
                  <Badge 
                    variant="secondary"
                    className={
                      report.status === "ready" ? "bg-chart-2 text-chart-2-foreground" :
                      report.status === "generating" ? "bg-chart-3 text-chart-3-foreground" :
                      "bg-destructive text-destructive-foreground"
                    }
                  >
                    {report.status.charAt(0).toUpperCase() + report.status.slice(1)}
                  </Badge>
                </div>
              </div>
            </CardHeader>
            
            <CardContent className="space-y-4">
              <div>
                <h4 className="text-sm font-medium mb-2">Report Sections</h4>
                <div className="flex flex-wrap gap-1">
                  {report.sections.map((section) => (
                    <Badge key={section} variant="outline" className="text-xs">
                      {section}
                    </Badge>
                  ))}
                </div>
              </div>

              {report.lastGenerated && (
                <div className="flex items-center justify-between text-sm text-muted-foreground">
                  <span>Last generated: {report.lastGenerated}</span>
                  {report.size && <span>Size: {report.size}</span>}
                </div>
              )}

              <div className="flex gap-2">
                {report.status === "ready" ? (
                  <>
                    <Button
                      size="sm"
                      onClick={() => handleDownload(report.id)}
                      data-testid={`button-download-${report.id}`}
                    >
                      <Download className="h-3 w-3 mr-1" />
                      Download
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => handlePreview(report)}
                      data-testid={`button-preview-${report.id}`}
                    >
                      <Eye className="h-3 w-3 mr-1" />
                      Preview
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => handleShare(report.id)}
                      data-testid={`button-share-${report.id}`}
                    >
                      <Share className="h-3 w-3 mr-1" />
                      Share
                    </Button>
                  </>
                ) : report.status === "generating" ? (
                  <Button size="sm" disabled>
                    Generating...
                  </Button>
                ) : (
                  <Button
                    size="sm"
                    onClick={() => handleGenerate(report.id)}
                    data-testid={`button-generate-${report.id}`}
                  >
                    Generate Report
                  </Button>
                )}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Custom Report Options</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <Button variant="outline" data-testid="button-custom-executive">
              <Mail className="h-4 w-4 mr-2" />
              Email Summary to Stakeholders
            </Button>
            <Button variant="outline" data-testid="button-custom-comparison">
              <FileText className="h-4 w-4 mr-2" />
              Generate Comparison Report
            </Button>
          </div>
        </CardContent>
      </Card>

      <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
        <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto" data-testid="dialog-report-preview">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5" />
              {previewReport?.title}
            </DialogTitle>
          </DialogHeader>
          
          {previewReport && (
            <div className="space-y-6">
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <Badge variant="outline">
                    {previewReport.format.toUpperCase()}
                  </Badge>
                  <Badge 
                    variant="secondary"
                    className={
                      previewReport.status === "ready" ? "bg-chart-2 text-chart-2-foreground" :
                      previewReport.status === "generating" ? "bg-chart-3 text-chart-3-foreground" :
                      "bg-destructive text-destructive-foreground"
                    }
                  >
                    {previewReport.status.charAt(0).toUpperCase() + previewReport.status.slice(1)}
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">
                  {previewReport.description}
                </p>
              </div>

              <div className="space-y-2">
                <h3 className="text-sm font-semibold">Report Metadata</h3>
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div>
                    <span className="text-muted-foreground">Assessment ID:</span>
                    <span className="ml-2 font-mono">{assessmentId}</span>
                  </div>
                  {previewReport.lastGenerated && (
                    <div>
                      <span className="text-muted-foreground">Last Generated:</span>
                      <span className="ml-2">{previewReport.lastGenerated}</span>
                    </div>
                  )}
                  {previewReport.size && (
                    <div>
                      <span className="text-muted-foreground">File Size:</span>
                      <span className="ml-2">{previewReport.size}</span>
                    </div>
                  )}
                  <div>
                    <span className="text-muted-foreground">Report ID:</span>
                    <span className="ml-2 font-mono">{previewReport.id}</span>
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <h3 className="text-sm font-semibold">Report Sections</h3>
                <div className="space-y-2">
                  {previewReport.sections.map((section, idx) => (
                    <div key={section} className="flex items-start gap-2 text-sm">
                      <span className="text-muted-foreground font-mono">{idx + 1}.</span>
                      <span>{section}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="border-t pt-4">
                <p className="text-xs text-muted-foreground">
                  {previewReport.format === 'pdf' && 
                    'This preview shows the report structure. The actual PDF will include formatted content, charts, and images.'
                  }
                  {previewReport.format === 'docx' && 
                    'This preview shows the report structure. The actual DOCX will include formatted content with proper styling.'
                  }
                  {previewReport.format === 'html' && 
                    'This preview shows the report structure. The actual HTML will include interactive elements and embedded charts.'
                  }
                </p>
              </div>

              <div className="flex gap-2 justify-end">
                <Button
                  variant="outline"
                  onClick={() => setPreviewOpen(false)}
                  data-testid="button-close-preview"
                >
                  Close
                </Button>
                <Button
                  onClick={() => {
                    handleDownload(previewReport.id);
                    setPreviewOpen(false);
                  }}
                  data-testid="button-download-from-preview"
                >
                  <Download className="h-3 w-3 mr-1" />
                  Download Report
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}