/**
 * Office Building Interview Questionnaire
 * Comprehensive 80+ question interview protocol for corporate office facilities
 * 13 sections with nested follow-ups, risk indicators, and threat/control mappings
 */

export interface InterviewQuestion {
  id: string;
  section: string;
  zoneApplicable?: string[];
  questionText: string;
  questionType: 'text' | 'multiple_choice' | 'rating' | 'yes_no' | 'checklist';
  options?: string[];
  ratingScale?: { min: number; max: number; labels: string[] };
  required: boolean;
  followUpQuestions?: InterviewQuestion[];
  riskIndicators?: string[];
  informsThreat?: string[];
  informsVulnerability?: boolean;
  informsImpact?: boolean;
  suggestsControls?: string[];
}

export const OFFICE_BUILDING_INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  // ========== SECTION 1: FACILITY OVERVIEW & OPERATIONS ==========
  {
    id: 'facility_overview_1',
    section: 'Facility Overview & Operations',
    questionText: 'What is the total square footage of this facility?',
    questionType: 'text',
    required: true,
    informsImpact: true,
  },
  {
    id: 'facility_overview_2',
    section: 'Facility Overview & Operations',
    questionText: 'How many employees work at this location?',
    questionType: 'multiple_choice',
    options: [
      '1-25 employees',
      '26-100 employees',
      '101-250 employees',
      '251-500 employees',
      '500+ employees',
    ],
    required: true,
    informsImpact: true,
  },
  {
    id: 'facility_overview_3',
    section: 'Facility Overview & Operations',
    questionText: 'What are the primary business operations conducted here?',
    questionType: 'checklist',
    options: [
      'Administrative/Corporate offices',
      'Research & Development',
      'Financial services/Banking',
      'Legal services',
      'Healthcare/Medical',
      'Technology/Software development',
      'Manufacturing/Production',
      'Customer service/Call center',
      'Data center operations',
      'Other (specify in notes)',
    ],
    required: true,
    informsThreat: ['theft_intellectual_property'],
    informsImpact: true,
  },
  {
    id: 'facility_overview_4',
    section: 'Facility Overview & Operations',
    questionText: 'What is the facility\'s classification regarding sensitive information?',
    questionType: 'multiple_choice',
    options: [
      'Handles classified government information',
      'Processes highly confidential corporate data (trade secrets, M&A)',
      'Standard corporate confidential information',
      'General business information only',
      'Public-facing operations with minimal sensitive data',
    ],
    required: true,
    informsThreat: ['theft_intellectual_property', 'espionage_surveillance'],
    informsImpact: true,
  },
  {
    id: 'facility_overview_5',
    section: 'Facility Overview & Operations',
    questionText: 'What are the facility\'s operating hours?',
    questionType: 'multiple_choice',
    options: [
      '24/7 operations',
      'Extended hours (6 AM - 10 PM)',
      'Standard business hours (8 AM - 6 PM)',
      'Limited hours (9 AM - 5 PM)',
      'Varies by department',
    ],
    required: true,
    informsVulnerability: true,
  },
  {
    id: 'facility_overview_6',
    section: 'Facility Overview & Operations',
    questionText: 'How many employees typically work after standard business hours (after 6 PM)?',
    questionType: 'multiple_choice',
    options: [
      'None - building closed',
      '1-10 employees',
      '11-25 employees',
      '26-50 employees',
      '50+ employees',
    ],
    required: true,
    informsVulnerability: true,
    informsThreat: ['workplace_violence_active_threat'],
    riskIndicators: ['None', '1-10'],
  },
  {
    id: 'facility_overview_7',
    section: 'Facility Overview & Operations',
    questionText: 'Does the facility have high-value equipment or assets?',
    questionType: 'yes_no',
    required: true,
    informsThreat: ['theft_property'],
    followUpQuestions: [
      {
        id: 'facility_overview_7a',
        section: 'Facility Overview & Operations',
        questionText: 'What types of high-value assets are present? (Select all that apply)',
        questionType: 'checklist',
        options: [
          'Computer equipment and servers',
          'Laboratory equipment',
          'Manufacturing equipment',
          'Medical equipment',
          'Audio/Visual equipment',
          'Company vehicles',
          'Prototypes or product samples',
          'Cash or negotiable instruments',
        ],
        required: true,
        informsImpact: true,
      },
      {
        id: 'facility_overview_7b',
        section: 'Facility Overview & Operations',
        questionText: 'What is the approximate total value of portable equipment/assets?',
        questionType: 'multiple_choice',
        options: [
          'Less than $50,000',
          '$50,000 - $250,000',
          '$250,000 - $1 million',
          '$1 million - $5 million',
          'Over $5 million',
        ],
        required: true,
        informsImpact: true,
      },
    ],
  },

  // ========== SECTION 2: PERIMETER SECURITY ==========
  {
    id: 'perimeter_1',
    section: 'Perimeter Security',
    zoneApplicable: ['perimeter'],
    questionText: 'Is the property boundary clearly defined?',
    questionType: 'multiple_choice',
    options: [
      'Yes - fenced perimeter',
      'Yes - natural boundary (landscaping, terrain)',
      'Yes - building walls form perimeter',
      'No - open/undefined boundary',
    ],
    required: true,
    informsVulnerability: true,
    informsThreat: ['forced_entry', 'vandalism'],
    riskIndicators: ['No - open'],
    suggestsControls: ['Perimeter Fencing - Chain Link'],
  },
  {
    id: 'perimeter_2',
    section: 'Perimeter Security',
    zoneApplicable: ['perimeter'],
    questionText: 'If fenced, what is the fence height and type?',
    questionType: 'multiple_choice',
    options: [
      'No fence present',
      'Decorative/low fence (under 4 ft)',
      'Standard chain-link (6-8 ft)',
      'High security fence (8+ ft) with anti-climb features',
      'Reinforced/hardened perimeter barrier',
    ],
    required: true,
    informsVulnerability: true,
    riskIndicators: ['No fence', 'Decorative'],
    suggestsControls: ['Perimeter Fencing - Anti-Climb'],
  },
  {
    id: 'perimeter_3',
    section: 'Perimeter Security',
    zoneApplicable: ['perimeter'],
    questionText: 'Are there perimeter intrusion detection systems?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    suggestsControls: ['Motion Detectors - PIR'],
    followUpQuestions: [
      {
        id: 'perimeter_3a',
        section: 'Perimeter Security',
        questionText: 'What type of perimeter detection is installed?',
        questionType: 'checklist',
        options: [
          'Fence-mounted sensors',
          'Buried cable sensors',
          'Infrared/laser beams',
          'Video analytics on perimeter cameras',
          'Motion sensors',
        ],
        required: true,
      },
    ],
  },
  {
    id: 'perimeter_4',
    section: 'Perimeter Security',
    zoneApplicable: ['perimeter'],
    questionText: 'Is perimeter lighting adequate for nighttime security?',
    questionType: 'rating',
    ratingScale: {
      min: 1,
      max: 5,
      labels: ['No lighting', 'Poor lighting', 'Adequate', 'Good', 'Excellent'],
    },
    required: true,
    informsVulnerability: true,
    riskIndicators: ['1', '2'],
    suggestsControls: ['Perimeter Lighting'],
  },
  {
    id: 'perimeter_5',
    section: 'Perimeter Security',
    zoneApplicable: ['perimeter'],
    questionText: 'Are there clear zones maintained around the building perimeter?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    suggestsControls: ['CPTED Principles - Clear Zones'],
    followUpQuestions: [
      {
        id: 'perimeter_5a',
        section: 'Perimeter Security',
        questionText: 'Approximately how many feet is the clear zone around the building?',
        questionType: 'multiple_choice',
        options: [
          'Less than 5 feet',
          '5-10 feet',
          '10-15 feet',
          '15-25 feet',
          '25+ feet',
        ],
        required: true,
        riskIndicators: ['Less than 5'],
      },
    ],
  },
  {
    id: 'perimeter_6',
    section: 'Perimeter Security',
    zoneApplicable: ['perimeter'],
    questionText: 'Are landscaping elements maintained to prevent concealment?',
    questionType: 'multiple_choice',
    options: [
      'Yes - vegetation kept below 3 ft near building',
      'Partially - some overgrown areas exist',
      'No - significant concealment opportunities',
      'Not applicable - no vegetation',
    ],
    required: true,
    informsVulnerability: true,
    riskIndicators: ['No - significant'],
    suggestsControls: ['CPTED Principles - Clear Zones'],
  },
  {
    id: 'perimeter_7',
    section: 'Perimeter Security',
    zoneApplicable: ['perimeter'],
    questionText: 'Are CCTV cameras covering the perimeter?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    suggestsControls: ['CCTV System - Outdoor'],
    followUpQuestions: [
      {
        id: 'perimeter_7a',
        section: 'Perimeter Security',
        questionText: 'What percentage of the perimeter has camera coverage?',
        questionType: 'multiple_choice',
        options: [
          'Complete (100%)',
          'Most areas (75-99%)',
          'Partial coverage (50-74%)',
          'Limited coverage (25-49%)',
          'Minimal coverage (<25%)',
        ],
        required: true,
        riskIndicators: ['Limited', 'Minimal'],
      },
      {
        id: 'perimeter_7b',
        section: 'Perimeter Security',
        questionText: 'Are perimeter cameras monitored in real-time or recording only?',
        questionType: 'multiple_choice',
        options: [
          'Real-time monitoring 24/7',
          'Real-time monitoring during business hours only',
          'Recording only - reviewed after incidents',
          'Recording only - rarely reviewed',
        ],
        required: true,
        riskIndicators: ['rarely reviewed'],
        suggestsControls: ['Video Monitoring Station'],
      },
    ],
  },

  // ========== SECTION 3: PARKING FACILITIES ==========
  {
    id: 'parking_1',
    section: 'Parking Facilities',
    zoneApplicable: ['parking'],
    questionText: 'What type of parking does the facility provide?',
    questionType: 'checklist',
    options: [
      'Surface parking lot',
      'Multi-level parking structure',
      'Underground parking garage',
      'Street parking only',
      'No dedicated parking',
    ],
    required: true,
  },
  {
    id: 'parking_2',
    section: 'Parking Facilities',
    zoneApplicable: ['parking'],
    questionText: 'Is parking access controlled?',
    questionType: 'multiple_choice',
    options: [
      'Yes - gate with badge/card access',
      'Yes - gate with attendant/security',
      'Yes - permit system with visual verification',
      'No - open access',
    ],
    required: true,
    informsVulnerability: true,
    informsThreat: ['forced_entry', 'theft_property', 'workplace_violence_domestic'],
    riskIndicators: ['No - open'],
    suggestsControls: ['Card Access System', 'Security Officers - Unarmed'],
  },
  {
    id: 'parking_3',
    section: 'Parking Facilities',
    zoneApplicable: ['parking'],
    questionText: 'Rate the lighting in parking areas:',
    questionType: 'rating',
    ratingScale: {
      min: 1,
      max: 5,
      labels: ['Very poor', 'Poor', 'Adequate', 'Good', 'Excellent'],
    },
    required: true,
    informsVulnerability: true,
    riskIndicators: ['1', '2'],
    suggestsControls: ['Parking Lot Lighting'],
  },
  {
    id: 'parking_4',
    section: 'Parking Facilities',
    zoneApplicable: ['parking'],
    questionText: 'Are parking areas monitored by CCTV?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    suggestsControls: ['CCTV System - Outdoor'],
    followUpQuestions: [
      {
        id: 'parking_4a',
        section: 'Parking Facilities',
        questionText: 'What is the camera coverage in parking areas?',
        questionType: 'multiple_choice',
        options: [
          'Comprehensive coverage of all areas',
          'Coverage of entry/exit points only',
          'Partial coverage with blind spots',
          'Minimal coverage',
        ],
        required: true,
        riskIndicators: ['Partial', 'Minimal'],
      },
    ],
  },
  {
    id: 'parking_5',
    section: 'Parking Facilities',
    zoneApplicable: ['parking'],
    questionText: 'Have there been security incidents in parking areas in the past 12 months?',
    questionType: 'yes_no',
    required: true,
    informsThreat: ['theft_property', 'vandalism', 'workplace_violence_domestic'],
    followUpQuestions: [
      {
        id: 'parking_5a',
        section: 'Parking Facilities',
        questionText: 'What types of incidents have occurred? (Select all that apply)',
        questionType: 'checklist',
        options: [
          'Vehicle break-ins/theft from vehicles',
          'Vehicle theft',
          'Vandalism to vehicles',
          'Personal assaults or threats',
          'Suspicious persons/loitering',
          'Accidents/safety incidents',
        ],
        required: true,
        riskIndicators: ['break-ins', 'theft', 'assaults'],
      },
      {
        id: 'parking_5b',
        section: 'Parking Facilities',
        questionText: 'How many incidents occurred in the past 12 months?',
        questionType: 'multiple_choice',
        options: ['1-2', '3-5', '6-10', '10+'],
        required: true,
        riskIndicators: ['6-10', '10+'],
      },
    ],
  },
  {
    id: 'parking_6',
    section: 'Parking Facilities',
    zoneApplicable: ['parking'],
    questionText: 'Is there security patrol coverage of parking areas?',
    questionType: 'multiple_choice',
    options: [
      'Yes - 24/7 coverage',
      'Yes - during business hours only',
      'Yes - periodic random patrols',
      'No security patrol',
    ],
    required: true,
    informsVulnerability: true,
    suggestsControls: ['Mobile Patrol'],
  },

  // ========== SECTION 4: BUILDING ENTRY POINTS & LOBBY ==========
  {
    id: 'entry_1',
    section: 'Building Entry Points & Lobby',
    zoneApplicable: ['lobby'],
    questionText: 'How many public entry points does the building have during business hours?',
    questionType: 'multiple_choice',
    options: [
      'One main entrance only',
      '2-3 entrances',
      '4-5 entrances',
      'More than 5 entrances',
    ],
    required: true,
    informsVulnerability: true,
    riskIndicators: ['More than 5'],
  },
  {
    id: 'entry_2',
    section: 'Building Entry Points & Lobby',
    zoneApplicable: ['lobby'],
    questionText: 'Is there a staffed reception desk at the main entrance?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    informsThreat: ['tailgating', 'piggybacking'],
    suggestsControls: ['Reception/Concierge Staff'],
    followUpQuestions: [
      {
        id: 'entry_2a',
        section: 'Building Entry Points & Lobby',
        questionText: 'What are the reception desk operating hours?',
        questionType: 'multiple_choice',
        options: [
          '24/7 coverage',
          'Extended hours (6 AM - 10 PM)',
          'Business hours only (8 AM - 6 PM)',
          'Limited hours',
        ],
        required: true,
        riskIndicators: ['Limited hours'],
      },
    ],
  },
  {
    id: 'entry_3',
    section: 'Building Entry Points & Lobby',
    zoneApplicable: ['lobby'],
    questionText: 'What type of access control is used at main entry points?',
    questionType: 'multiple_choice',
    options: [
      'Badge/card reader with turnstiles or speed gates',
      'Badge/card reader on doors (no physical barriers)',
      'Security guard verification only',
      'Open access during business hours',
    ],
    required: true,
    informsVulnerability: true,
    informsThreat: ['tailgating', 'piggybacking', 'forced_entry'],
    riskIndicators: ['Open access'],
    suggestsControls: ['Card Access System', 'Turnstiles/Speed Gates'],
  },
  {
    id: 'entry_4',
    section: 'Building Entry Points & Lobby',
    zoneApplicable: ['lobby'],
    questionText: 'Does the access control system prevent tailgating?',
    questionType: 'multiple_choice',
    options: [
      'Yes - physical barriers (turnstiles, man trap, speed gates)',
      'Partial - card readers with anti-passback but no physical barrier',
      'No - card readers only, no tailgating prevention',
      'No access control system',
    ],
    required: true,
    informsVulnerability: true,
    informsThreat: ['tailgating', 'piggybacking'],
    riskIndicators: ['No - card readers only', 'No access control'],
    suggestsControls: ['Turnstiles/Speed Gates', 'Man Trap/Vestibule'],
  },
  {
    id: 'entry_5',
    section: 'Building Entry Points & Lobby',
    zoneApplicable: ['lobby'],
    questionText: 'Is there a visitor management system?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    informsThreat: ['tailgating'],
    suggestsControls: ['Visitor Management System'],
    followUpQuestions: [
      {
        id: 'entry_5a',
        section: 'Building Entry Points & Lobby',
        questionText: 'Describe the visitor management process: (Select all that apply)',
        questionType: 'checklist',
        options: [
          'Photo ID required and scanned',
          'Visitor badge issued',
          'Host notification (call/text/email)',
          'Sign-in log maintained',
          'Escort required at all times',
          'Background check for contractors/vendors',
        ],
        required: true,
      },
      {
        id: 'entry_5b',
        section: 'Building Entry Points & Lobby',
        questionText: 'Are visitors required to be escorted?',
        questionType: 'multiple_choice',
        options: [
          'Yes - always escorted',
          'Yes - escorted to sensitive areas only',
          'No - visitors can move freely once signed in',
        ],
        required: true,
        riskIndicators: ['No - visitors can move freely'],
      },
    ],
  },
  {
    id: 'entry_6',
    section: 'Building Entry Points & Lobby',
    zoneApplicable: ['lobby'],
    questionText: 'How many visitors does the facility receive on an average day?',
    questionType: 'multiple_choice',
    options: [
      'Very few (1-10)',
      'Moderate (11-25)',
      'Moderate-High (26-50)',
      'High volume (51-100)',
      'Very high volume (100+)',
    ],
    required: true,
    informsVulnerability: true,
  },

  // ========== SECTION 5: INTERIOR ACCESS CONTROL ==========
  {
    id: 'interior_1',
    section: 'Interior Access Control',
    zoneApplicable: ['office_area'],
    questionText: 'Is badge access required to enter office areas beyond the lobby?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    informsThreat: ['tailgating', 'theft_property'],
    suggestsControls: ['Card Access System'],
  },
  {
    id: 'interior_2',
    section: 'Interior Access Control',
    zoneApplicable: ['executive_suite', 'server_room'],
    questionText: 'Are sensitive areas (server rooms, executive suites, HR) protected by enhanced access control?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    informsThreat: ['theft_intellectual_property', 'sabotage'],
    suggestsControls: ['Biometric Access Control'],
    followUpQuestions: [
      {
        id: 'interior_2a',
        section: 'Interior Access Control',
        questionText: 'What type of enhanced access control is used?',
        questionType: 'checklist',
        options: [
          'Biometric (fingerprint, facial recognition)',
          'Card + PIN combination',
          'Man trap/security vestibule',
          'Security guard stationed at entrance',
          'Additional badge reader only',
        ],
        required: true,
      },
    ],
  },
  {
    id: 'interior_3',
    section: 'Interior Access Control',
    questionText: 'Are access rights regularly audited and updated?',
    questionType: 'multiple_choice',
    options: [
      'Yes - quarterly audits',
      'Yes - annually',
      'Yes - on termination/transfer only',
      'No formal audit process',
    ],
    required: true,
    informsVulnerability: true,
    riskIndicators: ['No formal audit'],
    suggestsControls: ['Access Control Policy & Audit'],
  },
  {
    id: 'interior_4',
    section: 'Interior Access Control',
    questionText: 'Is there a policy requiring employees to display badges while on premises?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    suggestsControls: ['Badge Display Policy'],
  },

  // ========== SECTION 6: SURVEILLANCE SYSTEMS ==========
  {
    id: 'surveillance_1',
    section: 'Surveillance Systems',
    questionText: 'Are CCTV cameras installed inside the facility?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    suggestsControls: ['CCTV System - IP/Network'],
    followUpQuestions: [
      {
        id: 'surveillance_1a',
        section: 'Surveillance Systems',
        questionText: 'What areas are covered by interior cameras?',
        questionType: 'checklist',
        options: [
          'All building entrances/exits',
          'Elevator lobbies',
          'Main corridors',
          'Stairwells',
          'Parking garage access points',
          'Server room/IT areas',
          'Sensitive work areas',
          'Loading dock/receiving',
        ],
        required: true,
      },
      {
        id: 'surveillance_1b',
        section: 'Surveillance Systems',
        questionText: 'What is the camera resolution quality?',
        questionType: 'multiple_choice',
        options: [
          'High definition (1080p or better)',
          'Standard definition (720p)',
          'Low resolution/analog',
          'Mixed - some HD, some standard',
        ],
        required: true,
        riskIndicators: ['Low resolution'],
      },
    ],
  },
  {
    id: 'surveillance_2',
    section: 'Surveillance Systems',
    questionText: 'Is CCTV footage monitored in real-time or recording only?',
    questionType: 'multiple_choice',
    options: [
      'Real-time monitoring 24/7 at security operations center',
      'Real-time monitoring during business hours',
      'Recording only - reviewed after incidents',
      'Recording only - rarely reviewed',
    ],
    required: true,
    informsVulnerability: true,
    riskIndicators: ['rarely reviewed'],
    suggestsControls: ['Video Monitoring Station'],
  },
  {
    id: 'surveillance_3',
    section: 'Surveillance Systems',
    questionText: 'How long is CCTV footage retained?',
    questionType: 'multiple_choice',
    options: [
      '90+ days',
      '30-89 days',
      '7-29 days',
      'Less than 7 days',
    ],
    required: true,
    riskIndicators: ['Less than 7'],
  },

  // ========== SECTION 7: INTRUSION DETECTION & ALARM SYSTEMS ==========
  {
    id: 'intrusion_1',
    section: 'Intrusion Detection & Alarm Systems',
    questionText: 'Is an intrusion alarm system installed?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    informsThreat: ['forced_entry'],
    suggestsControls: ['Alarm Monitoring Service'],
    followUpQuestions: [
      {
        id: 'intrusion_1a',
        section: 'Intrusion Detection & Alarm Systems',
        questionText: 'What types of sensors are installed?',
        questionType: 'checklist',
        options: [
          'Door/window contacts',
          'Motion detectors (PIR)',
          'Glass break sensors',
          'Perimeter sensors',
        ],
        required: true,
      },
      {
        id: 'intrusion_1b',
        section: 'Intrusion Detection & Alarm Systems',
        questionText: 'Is the alarm system monitored by a third-party monitoring center?',
        questionType: 'yes_no',
        required: true,
        suggestsControls: ['Alarm Monitoring Service'],
      },
    ],
  },
  {
    id: 'intrusion_2',
    section: 'Intrusion Detection & Alarm Systems',
    questionText: 'Are intrusion alarms tested regularly?',
    questionType: 'multiple_choice',
    options: [
      'Yes - monthly',
      'Yes - quarterly',
      'Yes - annually',
      'No regular testing',
    ],
    required: true,
    riskIndicators: ['No regular testing'],
  },

  // ========== SECTION 8: SECURITY PERSONNEL & PROCEDURES ==========
  {
    id: 'personnel_1',
    section: 'Security Personnel & Procedures',
    questionText: 'Are security officers or guards employed at the facility?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    suggestsControls: ['Security Officers - Unarmed'],
    followUpQuestions: [
      {
        id: 'personnel_1a',
        section: 'Security Personnel & Procedures',
        questionText: 'What is the security staffing model?',
        questionType: 'multiple_choice',
        options: [
          '24/7 coverage with multiple officers',
          '24/7 single officer',
          'Business hours only',
          'Part-time/on-call',
        ],
        required: true,
      },
      {
        id: 'personnel_1b',
        section: 'Security Personnel & Procedures',
        questionText: 'Are security officers armed or unarmed?',
        questionType: 'multiple_choice',
        options: ['Armed', 'Unarmed', 'Mix of armed and unarmed'],
        required: true,
      },
    ],
  },
  {
    id: 'personnel_2',
    section: 'Security Personnel & Procedures',
    questionText: 'Are background checks conducted on all employees?',
    questionType: 'multiple_choice',
    options: [
      'Yes - all employees',
      'Yes - employees with access to sensitive areas only',
      'Yes - management and above only',
      'No formal background check program',
    ],
    required: true,
    informsVulnerability: true,
    riskIndicators: ['No formal background'],
    suggestsControls: ['Background Checks'],
  },
  {
    id: 'personnel_3',
    section: 'Security Personnel & Procedures',
    questionText: 'Do employees receive security awareness training?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    suggestsControls: ['Security Awareness Training'],
    followUpQuestions: [
      {
        id: 'personnel_3a',
        section: 'Security Personnel & Procedures',
        questionText: 'How often is security awareness training conducted?',
        questionType: 'multiple_choice',
        options: [
          'Annually for all employees',
          'During onboarding only',
          'Periodically (no set schedule)',
          'Ad-hoc when incidents occur',
        ],
        required: true,
      },
    ],
  },

  // ========== SECTION 9: EMERGENCY PREPAREDNESS & RESPONSE ==========
  {
    id: 'emergency_1',
    section: 'Emergency Preparedness & Response',
    questionText: 'Does the facility have a written emergency response plan?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    informsThreat: ['workplace_violence_active_threat'],
    suggestsControls: ['Incident Response Plan'],
  },
  {
    id: 'emergency_2',
    section: 'Emergency Preparedness & Response',
    questionText: 'Are evacuation drills conducted?',
    questionType: 'multiple_choice',
    options: [
      'Yes - quarterly',
      'Yes - semi-annually',
      'Yes - annually',
      'No regular drills',
    ],
    required: true,
    riskIndicators: ['No regular drills'],
  },
  {
    id: 'emergency_3',
    section: 'Emergency Preparedness & Response',
    questionText: 'Has the facility conducted active threat (active shooter) response training?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    informsThreat: ['workplace_violence_active_threat'],
    suggestsControls: ['Active Threat Response Training'],
  },
  {
    id: 'emergency_4',
    section: 'Emergency Preparedness & Response',
    questionText: 'Is there a mass notification system to alert occupants?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    followUpQuestions: [
      {
        id: 'emergency_4a',
        section: 'Emergency Preparedness & Response',
        questionText: 'What notification methods are used?',
        questionType: 'checklist',
        options: [
          'PA system/speakers',
          'Email alerts',
          'SMS/text messaging',
          'Mobile app notifications',
          'Desktop pop-ups',
          'Visual alerts (strobes, digital signage)',
        ],
        required: true,
      },
    ],
  },

  // ========== SECTION 10: INCIDENT HISTORY ==========
  {
    id: 'incident_history_1',
    section: 'Incident History',
    questionText: 'Have there been any security incidents at this facility in the past 12 months?',
    questionType: 'yes_no',
    required: true,
    followUpQuestions: [
      {
        id: 'incident_history_1a',
        section: 'Incident History',
        questionText: 'What types of incidents have occurred? (Select all that apply)',
        questionType: 'checklist',
        options: [
          'Unauthorized entry/intrusion',
          'Theft of company property',
          'Theft of personal property',
          'Vandalism',
          'Workplace violence (threat or actual)',
          'Active threat/active shooter',
          'Domestic violence spillover',
          'Cyber incident with physical component',
          'Other',
        ],
        required: true,
        informsThreat: [
          'forced_entry',
          'tailgating',
          'piggybacking',
          'theft_property',
          'vandalism',
          'workplace_violence_employee',
          'workplace_violence_active_threat',
          'workplace_violence_domestic',
          'cyber_physical_access_hack',
        ],
      },
      {
        id: 'incident_history_1b',
        section: 'Incident History',
        questionText: 'How many incidents occurred in the past 12 months?',
        questionType: 'multiple_choice',
        options: ['1-2 incidents', '3-5 incidents', '6-10 incidents', '10+ incidents'],
        required: true,
        riskIndicators: ['6-10', '10+'],
      },
    ],
  },
  {
    id: 'incident_history_2',
    section: 'Incident History',
    questionText: 'Are security incidents formally documented and tracked?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
  },
  {
    id: 'incident_history_3',
    section: 'Incident History',
    questionText: 'Have there been any threats or concerning communications directed at the facility or employees?',
    questionType: 'yes_no',
    required: true,
    informsThreat: ['workplace_violence_active_threat', 'workplace_violence_employee'],
  },

  // ========== SECTION 11: CYBER-PHYSICAL SECURITY ==========
  {
    id: 'cyber_1',
    section: 'Cyber-Physical Security',
    questionText: 'Are physical security systems (access control, CCTV) on a segmented network separate from corporate IT?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    informsThreat: ['cyber_physical_access_hack', 'cyber_physical_cctv'],
    suggestsControls: ['Network Segmentation'],
  },
  {
    id: 'cyber_2',
    section: 'Cyber-Physical Security',
    questionText: 'Do security systems require multi-factor authentication for administrative access?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    suggestsControls: ['Multi-Factor Authentication'],
  },
  {
    id: 'cyber_3',
    section: 'Cyber-Physical Security',
    questionText: 'Are security system firmware and software regularly patched?',
    questionType: 'multiple_choice',
    options: [
      'Yes - automated patch management',
      'Yes - manual patching on regular schedule',
      'Occasionally - no set schedule',
      'Rarely or never patched',
    ],
    required: true,
    informsVulnerability: true,
    riskIndicators: ['Rarely or never'],
    suggestsControls: ['Security System Patch Management'],
  },

  // ========== SECTION 12: PHYSICAL DOCUMENT & DATA SECURITY ==========
  {
    id: 'document_1',
    section: 'Physical Document & Data Security',
    questionText: 'Is there a clean desk policy requiring employees to secure documents?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
    informsThreat: ['theft_intellectual_property', 'espionage_surveillance'],
    suggestsControls: ['Clean Desk Policy'],
  },
  {
    id: 'document_2',
    section: 'Physical Document & Data Security',
    questionText: 'Are secure document destruction services (shredders, locked bins) available?',
    questionType: 'yes_no',
    required: true,
    informsVulnerability: true,
  },

  // ========== SECTION 13: LOADING DOCK & RECEIVING ==========
  {
    id: 'loading_1',
    section: 'Loading Dock & Receiving',
    zoneApplicable: ['loading_dock'],
    questionText: 'Does the facility have a loading dock or receiving area?',
    questionType: 'yes_no',
    required: true,
    followUpQuestions: [
      {
        id: 'loading_1a',
        section: 'Loading Dock & Receiving',
        questionText: 'Is access to the loading dock controlled and restricted?',
        questionType: 'yes_no',
        required: true,
        informsVulnerability: true,
        suggestsControls: ['Card Access System'],
      },
      {
        id: 'loading_1b',
        section: 'Loading Dock & Receiving',
        questionText: 'Are deliveries logged and verified?',
        questionType: 'yes_no',
        required: true,
        informsVulnerability: true,
      },
      {
        id: 'loading_1c',
        section: 'Loading Dock & Receiving',
        questionText: 'Is CCTV surveillance installed at the loading dock?',
        questionType: 'yes_no',
        required: true,
        informsVulnerability: true,
        suggestsControls: ['CCTV System - Outdoor'],
      },
      {
        id: 'loading_1d',
        section: 'Loading Dock & Receiving',
        questionText: 'Are vendor/driver credentials verified before granting access?',
        questionType: 'yes_no',
        required: true,
        informsVulnerability: true,
        suggestsControls: ['Visitor Management System'],
      },
    ],
  },
];

// Extract unique sections for navigation
export const INTERVIEW_SECTIONS = Array.from(
  new Set(OFFICE_BUILDING_INTERVIEW_QUESTIONS.map(q => q.section))
);

// Threat-to-Control mapping for auto-recommendations
export const OFFICE_THREAT_CONTROL_MAPPING: Record<string, string[]> = {
  forced_entry: [
    'Perimeter Fencing - Chain Link',
    'Reinforced Doors/Frames',
    'Alarm Monitoring Service',
    'Glass Break Sensors',
    'Perimeter Lighting',
    'CCTV System - Outdoor',
  ],
  tailgating: [
    'Turnstiles/Speed Gates',
    'Man Trap/Vestibule',
    'Reception/Concierge Staff',
    'Visitor Management System',
    'Badge Display Policy',
    'CCTV System - IP/Network',
    'Security Awareness Training',
  ],
  piggybacking: [
    'Turnstiles/Speed Gates',
    'Man Trap/Vestibule',
    'Reception/Concierge Staff',
    'Badge Display Policy',
    'Security Awareness Training',
  ],
  theft_property: [
    'Card Access System',
    'CCTV System - IP/Network',
    'CCTV System - Outdoor',
    'Video Monitoring Station',
    'Mobile Patrol',
    'Alarm Monitoring Service',
    'Motion Detectors - PIR',
    'Perimeter Lighting',
  ],
  theft_intellectual_property: [
    'Card Access System',
    'Biometric Access Control',
    'Visitor Management System',
    'Clean Desk Policy',
    'Background Checks',
    'Access Control Policy & Audit',
    'CCTV System - IP/Network',
    'Visitor Escort Policy',
  ],
  vandalism: [
    'Perimeter Fencing - Chain Link',
    'Perimeter Lighting',
    'CCTV System - Outdoor',
    'Mobile Patrol',
    'Security Signage',
  ],
  sabotage: [
    'Card Access System',
    'Biometric Access Control',
    'Background Checks',
    'Visitor Management System',
    'CCTV System - IP/Network',
    'Access Control Policy & Audit',
  ],
  workplace_violence_active_threat: [
    'Incident Response Plan',
    'Active Threat Response Training',
    'Video Monitoring Station',
    'Card Access System',
    'Visitor Management System',
    'Reception/Concierge Staff',
    'Mobile Patrol',
  ],
  workplace_violence_employee: [
    'Background Checks',
    'Security Awareness Training',
    'Incident Response Plan',
    'CCTV System - IP/Network',
  ],
  workplace_violence_domestic: [
    'Visitor Management System',
    'Reception/Concierge Staff',
    'Card Access System',
    'CCTV System - Outdoor',
  ],
  cyber_physical_access_hack: [
    'Network Segmentation',
    'Multi-Factor Authentication',
    'Security System Patch Management',
    'Access Control Policy & Audit',
  ],
  cyber_physical_cctv: [
    'Network Segmentation',
    'Multi-Factor Authentication',
    'Security System Patch Management',
  ],
  espionage_surveillance: [
    'Visitor Management System',
    'Clean Desk Policy',
    'Card Access System',
    'Biometric Access Control',
    'CCTV System - IP/Network',
    'Background Checks',
  ],
};
